### ISSUE TITLE
StopR request generates 404

### ISSUE THREAD

**Issue by irees** [ODOT-PTS/TNExT#100]
The [Stops Report](http://tna.trilliumtransit.com:8080/TNAtoolAPI-Webapp/stopreport.html?agency=59&x=0.25&route=5228&n=chs&popYear=2010&nav=stateS-countyS-route&areaid=41001&type=0&dbindex=10) issues an API request that results in a 404 error:

http://tna.trilliumtransit.com:8090/TNAtoolAPI-Webapp/queries/transit/StopsR?agency=59&day=03/08/2018&route=5228&x=0.25&areaid=41001&type=0&key=0.8764877102309176&dbindex=10&popYear=2010&username=admin&geotype=NaN&geoid=null&rc=null&stime=null&etime=null

**Comment by PPaulsonOregonDOT** [comment]
@irees I would check this set of reports as well, it appears to be a different path to a similar issue:
Via the County Report->Benton County Agencies-> Routes Report -> Two Stop Reports

http://tna.trilliumtransit.com:8090/TNAtoolAPI-Webapp/stopreport.html?&agency=456&areaid=41003&type=0&x=0.25&n=cAs&dbindex=11&popYear=2010&geotype=-1&geoid=null&nav=stateS-countyS-agencyS&rc=-1

http://tna.trilliumtransit.com:8090/TNAtoolAPI-Webapp/stopreport.html?&agency=148&areaid=41003&type=0&x=0.25&n=cAs&dbindex=11&popYear=2010&geotype=-1&geoid=null&nav=stateS-countyS-agencyS&rc=-1

Counties Report -> Routes -> 2x Stops Report

http://tna.trilliumtransit.com:8090/TNAtoolAPI-Webapp/stopreport.html?agency=101&x=0.25&route=455&n=cAs&popYear=2010&nav=stateS-countyS-route&areaid=41005&type=0&dbindex=11

**Comment by irees** [comment]
There were several issues with incorrect types and missing query parameters in the report. The above PR should fix all the stops reports mentioned in this issue.

**Comment by PPaulsonOregonDOT** [comment]
This report, the stops report reached from the agency summary report, seems to still have an issue.
http://oregon.tnext.io:8090/TNAtoolAPI-Webapp/stopreport.html?&agency=174&n=ecs&x=0.25&dbindex=12&popYear=2010&geotype=-1&geoid=null&areaid=null&type=null&route=null&nav=stateS-agencyS&rc=-1&stime=0:00&etime=23:59

**Comment by irees** [comment]
Fixed by #132
