### ISSUE TITLE
Timing Connection Report [re-design]

### ISSUE THREAD

**Issue by ODOT-RPTD-mb** [ODOT-PTS/TNExT#112]
Improve usability of timing connection report.

**Comment by PPaulsonOregonDOT** [comment]
Currently, this link does not provide any options in the agency drop down menu from any of the databases.
http://oregon.tnext.io:8090/TNAtoolAPI-Webapp/TimingConnection.html?&dbindex=12

**Comment by irees** [comment]
@PPaulsonOregonDOT Thanks for pointing this out - I saw it in testing earlier. It is a regression caused by agency selection and it will be fixed.

**Comment by irees** [comment]
Error in http://oregon.tnext.io:8090/TNAtoolAPI-Webapp/TimingConnection.html?&dbindex=12 fixed as part of #131

**Comment by PPaulsonOregonDOT** [comment]
One improvement that we have been discussing for a while that might build on the timing connections report work is a report that shows the average/total time that riders would spend transferring to and from services at a stop to identify "transfer friction", particularly through the Key Transit Hubs. From my limited understanding of the project, I think the valhalla routing engine might have some application here.
