### ISSUE TITLE
rename project to TNExT

### ISSUE THREAD

**Issue by drewda** [ODOT-PTS/TNExT#115]
- [x] @drewda: rename repository
- [x] @irees: update references to repository URL in `.git/config` files on Linode
- ~~update any `Dockerfile` references~~
- [x] change all instances of TNA to TNeXT
https://github.com/ODOT-PTS/TNAST_MAVEN/search?q=tna&type=Code
- [x] change "Transit Network Analysis" to "Transit Network Explorer"
https://github.com/ODOT-PTS/TNAST_MAVEN/search?utf8=%E2%9C%93&q=%22Transit+Network+Analysis%22&type=Code

//cc @ODOT-RPTD-mb @antrim

**Comment by ODOT-RPTD-mb** [comment]
If there is no compelling reason to touch /TNAtoolAPI-Webapp URLs, I am fine with no change.

**Comment by drewda** [comment]
It's just cosmetic, so we'll leave it be.

**Comment by drewda** [comment]
Now complete.
