### ISSUE TITLE
Calendar Reverting to current day in metadata

### ISSUE THREAD

**Issue by PPaulsonOregonDOT** [ODOT-PTS/TNExT#124]
It appears that the TNeXT tool may be reverting back to the current day when it is set to another day in the date selector. As an example, I'm attaching the metadata file for a Title VI report that I set to May 3rd, 2018 to predate the expiration of Cherriots GTFS feed. The service date selected shows up as 5/17/18, which is today, the day I ran the reports. It is hard to tell if this is simply a metadata issue or a fundamental error with the tool, because I don't currently have any data to compare this report to.
[Title VI Report-metaData.txt](https://github.com/ODOT-PTS/TNExT/files/2015066/Title.VI.Report-metaData.txt)

**Comment by irees** [comment]
The API request was made using the correct dates, but the values in metadata.txt used the initial values from when the page was loaded. This fix gets the correct values from the date widget.
