### ISSUE TITLE
Add Set Date Capacity for Reports Influenced by Expired Feeds

### ISSUE THREAD

**Issue by ODOT-RPTD-mb** [ODOT-PTS/TNExT#139]
@PPaulsonOregonDOT 
Summary reports typically do not support specification of report date, So as feeds expire there is not obvious method for user to get summary report for time period for which feeds were active.

For example:
https://oregon.tnext.io/TNAtoolAPI-Webapp/GeoPlacesReport.html?&dbindex=12&popYear=2010#

Explore setting map date, and changing client/user PC date as possible work-arounds.

**Comment by PPaulsonOregonDOT** [comment]
Generally, the summary reports don't show any data that is date dependent. For instance, in the report above, the summary report 558 urban stops, most of which are served by Cherriots, despite their feed expiring on 5/5/18.  I think the presumption that the tool works under is that when a feed expires, service stops, but that the physical stop locations are still in place. I don't think that this is a problem, except that it is not intuitive, so it is probably useful to add a note in the documentation somewhere.

**Comment by ODOT-RPTD-mb** [comment]
Never-mind temporary confusion RE: stops/visits
