### ISSUE TITLE
Title VI/Employment Time-out

### ISSUE THREAD

**Issue by PPaulsonOregonDOT** [ODOT-PTS/TNExT#140]
In  both the Oregon DOT environment and outside of it, it appears that the Title VI report: https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/Emp.html?&n=fAs&dbindex=12 and the employment report at https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/Emp.html?&n=fAs&dbindex=12 time out and do not complete their respective reports.

**Comment by PPaulsonOregonDOT** [comment]
We need to add the flexible reporting report at https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/FlexRep.html to the list of reports that is failing to complete, at least in the ODOT environment.

**Comment by PPaulsonOregonDOT** [comment]
In the last week, the Title VI report has been completing within  a minute or two. In doing further investigation, the employment report for the September 2017 database completes in a similar amount of time from both instances of the tool:
https://oregon.tnext.io/TNAtoolAPI-Webapp/Emp.html?&n=gjs&dbindex=10
https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/Emp.html?&n=gjs&dbindex=10

but does not complete when May 2018 is selected:
https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/Emp.html?&n=gjs&dbindex=12
https://oregon.tnext.io/TNAtoolAPI-Webapp/Emp.html?&n=gjs&dbindex=12&dataSet=lodes_blocks_wac&reportType=Counties&projectionYear=current&Sradius=0.25&LOS=2

Looking at the difference in the paths for the two reports that do not complete, is it possible that the report is trying to call a broken url?

**Comment by ODOT-RPTD-mb** [comment]
10/10/2018 oregon-staging.tnext.io; Sept 2018 db; title VI report is completing, employment report not completing.

**Comment by irees** [comment]
It looks like the Title VI report timeouts were related to the proxy configuration problem fixed in #144. The Employment report timeouts are in the database query itself, which pegs the database cpu at 100% and did not complete after an hour. I have the query copied out and debugging now.

**Comment by irees** [comment]
I improved the speed of the employment queries (should take about 5-10s now) by adding a spatial index on `lodes_blocks_wac.location`. I did this for all databases in both prod and dev. Not sure why the index was missing - when I create a new database locally from scratch, it is present.
