### ISSUE TITLE
Missing Route Miles

### ISSUE THREAD

**Issue by PPaulsonOregonDOT** [ODOT-PTS/TNExT#142]
In the extended reports data dump which I've attached, derived from the link below:
https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/Datadump.html?&n=gjs&dbindex=12&popYear=2010

there are a number of agencies (9 in total) that have 0 route miles listed, which is reflected in the extended reports of the individual agencies, accessed by this report:

https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/AgenSReport.html?&dbindex=12&popYear=2010#

Interestingly, the in looking at Columbia Area Transit's extended report:
https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/AgenXReport.html?&agency=37&x=0.25&l=2&n=gjs&dbindex=12&popYear=2010&areaid=null&type=0&username=admin&geotype=-1&geoid=null&nav=stateS-agencyS

the tool registers that there are service miles, and the route report for the same agency shows a series of routes with lengths and service hours associated with them:
https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/routereport.html?&agency=37&x=0.25&n=gjs&dbindex=12&popYear=2010&nav=stateS-agencyS

Given that these distances are registering in the tool, my best guess for the source of the problem is in how the tool is deciding which trip is the longest, which is then used in the calculations for route miles. I can't explain why only a subset of the agencies have this problem, other than to suggest that the problem might afflict agencies where all of the trips for a route are the same length, which I have to imagine is the case with the Aerial Tram, which is one of agencies with 0 route miles in this report.

The data dump report that started my hunt for this bug is listed below:
[Agencies_Extended_Reports_Dump7_10_2018.xlsx](https://github.com/ODOT-PTS/TNExT/files/2182772/Agencies_Extended_Reports_Dump7_10_2018.xlsx)

**Comment by irees** [comment]
Looks like the `gtfs_trip_segments` table is missing data for a couple agencies. This table is normally updated whenever a new feed is imported into the database, and is used get the correct lengths of route/geography intersections.

I'm looking into why it did not populate for these particular agencies. In the meantime I rebuilt the `gtfs_trip_segments` table with the following query:

```
TRUNCATE TABLE gtfs_trip_segments;
INSERT INTO gtfs_trip_segments (uid, agencyid, id, seg_id, shape)
SELECT ROW_NUMBER() OVER() AS uid,
    a.agencyid as agencyid,
    a.id AS id,
    n - 1 AS seg_id,
    ST_SetSRID(ST_MakeLine(ST_PointN(a.shape, n - 1), ST_PointN(a.shape, n)), 4326) AS shape
FROM gtfs_trips AS a
CROSS JOIN generate_series(2, ST_NPoints(a.shape)) AS n;
```
