### ISSUE TITLE
Aggregated Urban Areas detail report, with default values stall

### ISSUE THREAD

**Issue by ODOT-RPTD-mb** [ODOT-PTS/TNExT#144]
https://oregon.tnext.io/TNAtoolAPI-Webapp/GeoUrbansRXreport.html?&popMin=0&popMax=2000000&x=0.25&l=2&n=gEs&dbindex=12&popYear=2010&nav=stateS-AggUAS

Progress bar gets to 100% in a reasonable time, but fails to complete within 80+ minutes.

Will try again to see if can be replicated. 

![image](https://user-images.githubusercontent.com/8129162/43483096-76ff8a0c-94bf-11e8-8b43-f6bfc5d87820.png)

**Comment by PPaulsonOregonDOT** [comment]
It appears that this is only a problem for the production version of the tool. This following link, from the staging version of the tool, completes within a few minutes, with the same database settings and default settings as the link above:
https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/GeoUAreasRReport.html?&popMin=0&popMax=2000000&dbindex=12&popYear=2010

I also tested the urban areas report, which the aggregated urban report is built on and links to, and it appears to be working in both versions of the tool.

**Comment by irees** [comment]
Looks like the nginx reverse proxy that sits in front of both tnext dev & prod instances was missing timeout limits. 

The [underlying request](https://oregon.tnext.io/TNAtoolAPI-Webapp/queries/transit/UrbanrXR?&day=07/31/2018&key=0.7468148099410561&popYear=2010&username=admin&popMax=2000000&popMin=0&l=2&x=0.25) took slightly over 1 minute (1 minute and 3 seconds, to be exact), which was over the nginx default 1 minute timeout. (This proxy does ssl termination and virtual host resolution to the correct environment.)

I added timeouts to `/etc/nginx/conf.d/staging.conf` and `/etc/nginx/conf.d/prod.conf` and this should be resolved now.

```
        proxy_connect_timeout       3600;
        proxy_send_timeout          3600;
        proxy_read_timeout          3600;
        send_timeout                3600;
```
