### ISSUE TITLE
Extending user input parameter functionality range

### ISSUE THREAD

**Issue by ODOT-RPTD-mb** [ODOT-PTS/TNExT#150]
ODOT is reviewing range of functionality for report parameters, is interested in extending useful range. For example it would be nice if all reports were functional with one contiguous week selected.

**Comment by PPaulsonOregonDOT** [comment]
After recent indexing of reports, it appears that this issue has been largely resolved. I've attached a copy of the excel file that I've used to document my testing. There are a few reports that don't complete under certain circumstances, but the list of those reports has shrunk considerably.
[RevisedReportCompletionSheet.xlsx](https://github.com/ODOT-PTS/TNExT/files/2601874/RevisedReportCompletionSheet.xlsx)
