### ISSUE TITLE
Data Dump Report, screen feedback & duplicate agencies

### ISSUE THREAD

**Issue by ODOT-RPTD-mb** [ODOT-PTS/TNExT#153]
https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/Datadump.html?&n=jns&dbindex=13&popYear=2010

Modify date, and modify visits count. Select "generate report" no immediate screen feedback that report was selected. After waiting for an extended period (2+ minutes) selected generate report again and slide bar appears at right, slide down to see progress bar.

Duplicate listing of most but not all agencies in resultant file...?

Columbia Area Transit, Columbia County Rider,  Tillamook County Transit, Sandy Area Metro, etc. have 0 route miles, but do have service miles (see issue #142)

**Comment by PPaulsonOregonDOT** [comment]
I have been unable to replicate this behavior, and we believe it may be a result of double clicking results button. Should we close this issue?

**Comment by ODOT-RPTD-mb** [comment]
Have seen again, when re-starting data dump report (urban areas) before prior report is complete. This really should be fixed rather than ignored.
