### ISSUE TITLE
Feed Expiration Mismatch

### ISSUE THREAD

**Issue by PPaulsonOregonDOT** [ODOT-PTS/TNExT#157]
While I was following up on an issue similar to #142 that @ODOT-RPTD-mb noticed in the data dump report, I noticed that a number of seasonal services (Klamath Shuttle, Mt. Bachelor) had no service metrics listed in the agency extended report, which I would expect given that they are not operating right now. The behavior I wasn't expecting was that all of the agencies would still have valid feeds.

In double checking this behavior, I discovered that Mt. Bachelor's feed expired in the tool on 11/22/18, but in checking the feed on oregon-gtfs.com, feed-info.txt has the feed expiring on 10/30/18. Similar behavior was noted with the Klamath Shuttle. I would like to know more about how this mismatch occurred,(@antrim, @KalonThomas) to determine if this mismatch is a result of data cleaning or a bug in the tool.

**Comment by KalonThomas** [comment]
@PPaulsonOregonDOT -- Investigating the expiration mismatch on this end and will get back to you with findings.
