### ISSUE TITLE
Database Back ups

### ISSUE THREAD

**Issue by PPaulsonOregonDOT** [ODOT-PTS/TNExT#159]
I used the database dump link listed in the wiki for this project, and it took me to a google drive location which only had databases dating back to early 2016. If back-ups were not created for subsequent database, they should be created, and if they have been created, that portion of the wiki/metadata needs to be updated to reflect their location/conservator. Tagging @ed-g on this issue because it appears he opened a similar issue in #57.

**Comment by ed-g** [comment]
@PPaulsonOregonDOT there are multiple good options for backing up a database -- if you have an idea of how the backups will be used, who will need to make them /access them, and how many hours you want to spend setting up the system I'll can find some options.

Here's one option with the builtin tools:

https://www.postgresql.org/docs/10/backup.html

**Comment by PPaulsonOregonDOT** [comment]
I am hoping that this is a low resource endeavor, but I think the two main uses for the back-up will be for recovery purposes, for debugging issues that could result from a baseline data error or an error in who the tool is retrieving that data. I would personally be interested in having a database copy that I can test ad hoc or new queries against.
