### ISSUE TITLE
.csv export failure 

### ISSUE THREAD

**Issue by ODOT-RPTD-mb** [ODOT-PTS/TNExT#168]
@irees 
Many .csv exports do not seem to work. Counties Title VI Report does show directory window and creates file on .csv export. 
https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/T6.html?&n=avt&dbindex=13

Following reports are examples of not creating .csv files:
https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/ConAgenXReport.html?&gap=0.1&agency=101&dbindex=13

https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/GeoStateSreport.html?&dbindex=13&popYear=2010

https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/GeoPlacesReport.html?&dbindex=13&popYear=2010

https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/GeoCountiesReport.html?&dbindex=13&popYear=2010

**Comment by ODOT-RPTD-mb** [comment]
Phil can't duplicate .csv issue on his Windows 7 PC. I can on my ODOT Windows 10 PC.

**Comment by irees** [comment]
@ODOT-RPTD-mb This fix is now up on staging. 

Sorry it took an extra day - had to resolve an issue with a broken maven repository.
