### ISSUE TITLE
Reporting with a block population/employment density focus

### ISSUE THREAD

**Issue by ed-g** [ODOT-PTS/TNExT#17]
Reporting with a block pop density focus [Trillium leads this in consultation with OSU]

- For all reports with a stop radius parameter add a measure of pop density (pop per land area) based on blocks within specified block buffer. 
- Count block density only once.
- Is block area available from census or do we need to calculate?
- Any significant performance issues?
- If this data is new to TNA tool this might require touching a whole chain of program functionality from data import to UI and data export and everything in between.
- Related suggestions? From TNA tool final report document, it looks like 0 pop blocks are currently being dropped from db.
  * Ed, are you able to start work on this?

**Comment by ed-g** [comment]
Ask questions of the OSU team while making changes.

**Comment by PPaulsonOregonDOT** [comment]
I think this can probably be pushed back into we get an answer on Task #7, which will determine the level of value we would expect from implementing it.

**Comment by ODOT-RPTD-mb** [comment]
ODOT will review and if needed re-focus this task.

**Comment by ODOT-RPTD-mb** [comment]
Refining Issue:
For each report type that allows user to specify a stop radius; calculate and add to report results pop/employment/employees per area (acre) in reports. In cases of intersecting stop circles do not double count pop/employment/employees.

**Comment by ODOT-RPTD-mb** [comment]
@irees @drewda @PPaulsonOregonDOT 
Let's experiment with the "Statewide Extended Report" first.  Labels of new report values should have relevant mouse-over text.

**Comment by irees** [comment]
@ODOT-RPTD-mb 

I have added area served and population density rows to the "Statewide Extended Report." It is on staging for testing.

http://oregon.tnext.io:8090/TNAtoolAPI-Webapp/GeoStateXreport.html?&x=0.25&l=2&n=ecs&dbindex=12&areaId=41&popYear=2010&nav=stateS

![screenshot 2018-05-03 21 20 42](https://user-images.githubusercontent.com/720087/39613041-60dae5b4-4f19-11e8-9836-ad4d1357bfc7.png)

The same set of census blocks used to calculate "urban population served" goes into "urban area served" and "population density of urban area served." Likewise for rural. For employment density, the total area (urban+rural) is used.

The other reports in "Statewide Reports -> Geographical Reports" use the same api/query, so for these it is just a matter the table rows to the markup.

I added tooltips to the definition file but they aren't working just yet. Will fix that in next PR. I will also add area/density for "...served at level of service" (I have the query working).

**Comment by PPaulsonOregonDOT** [comment]
From this description, it appears that the area calculation comes from the area of the census blocks that are selected. If that assumption is correct, is it possible that changing the population radius or level of service parameter might not change the population or area figures if the same set of census blocks is selected?

**Comment by irees** [comment]
@PPaulsonOregonDOT 

Yes, the area is the total area of all census blocks selected. It is not the area of the census blocks intersected with the radius buffer around the stops.

This could be added. It would require multiplying the population/employment in each census block by the percentage area of the intersection. This may not be a totally valid assumption (that population/jobs is uniformly distributed across the census block), and would also add some complexity in the query. I can make this change if desired.

**Comment by PPaulsonOregonDOT** [comment]
@irees I don't think that the way this is calculated is problematic, I just want to make sure that I understand how it was working, and raise the question in case others have concerns.

**Comment by irees** [comment]
@PPaulsonOregonDOT OK. That was my thought as well, since the existing population values are calculated using whole census blocks. I'll go ahead and add the table rows to other reports that use the same `/geoAreaXR` query.

**Comment by ODOT-RPTD-mb** [comment]
@irees @PPaulsonOregonDOT @drewda  Assuming this represents a fairly trivial change.... let's mirror the Population Density fields with corresponding Employment and Employees fields, each with an Urban and Rural component. So we will have a total of eight density related fields;
The two Area Served (rural/urban) fields and two fields each for Population/Employment/Employees (rural/urban). We can drop the current combined Employees Density field, which can be calculated by the user as needed.

**Comment by ODOT-RPTD-mb** [comment]
@irees @PPaulsonOregonDOT @drewda I am realizing that I dropped our earlier conversation about the interaction of density and served at level of service. Also Phil provided some comments about possible simplification of results. I am going to take a more comprehensive look and likely modify my prior comment.

**Comment by ODOT-RPTD-mb** [comment]
@irees @PPaulsonOregonDOT @drewda
**_Reports should be revised to display and/or provide enough information to allow calculation, of this set of values:_**

Impacted by stop radius selection:

- Area served(1)
- Rural area served(1)
- Urban area served(1)

And by min level of service selected:

- 	Area served at level of service(1)(2)(3)
- 	Rural area served at level of service(1)(2)(3)
- 	Urban area served at level of service(1)(2)(3)

Applied to Population:

- 	Density of area served(1)
- 	Density of urban area served(1)
- 	Density of rural area served(1)

	Min level of service:

 	     Density of area served at level of service(1)(2)(3)
	     Density of rural area served at level of service(1)(2)(3)
	     Density of urban area served at level of service(1)(2)(3)

Applied to Employment:

- 	Density of area served(1)
- 	Density of urban area served(1)
- 	Density of rural area served(1)


	Min level of service:

 	     Density of area served at level of service(1)(2)(3)
	     Density of rural area served at level of service(1)(2)(3)
	     Density of urban area served at level of service(1)(2)(3)
Applied to Employees:

- 	Density of area served(1)
- 	Density of urban area served(1)
- 	Density of rural area served(1)


	Min level of service:

 	     Density of area served at level of service(1)(2)(3)
	     Density of rural area served at level of service(1)(2)(3)
	     Density of urban area served at level of service(1)(2)(3)

**Comment by irees** [comment]
Added for geographic reports. I included all of the breakouts requested by @ODOT-RPTD-mb. I initially attempted to present them in a table, with columns for "total, urban, rural" for each category -- but it did not play well with the existing table display. Instead they are all listed as rows in the main table; they can be filtered using the input field below the table. Tooltips are also included describing how each value is calculated.

County extended report
https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/GeoCountiesXreport.html?&areaid=41057&x=0.25&l=2&n=eys&dbindex=12&popYear=2010&nav=stateS-countyS

State extended report
https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/GeoStateXreport.html?&x=0.25&l=2&n=eys&dbindex=12&areaId=41&popYear=2010&nav=stateS

City extended report
https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/GeoPlacesXreport.html?&areaid=4159000&x=0.25&l=2&n=eys&dbindex=12&popYear=2010&nav=stateS-placeS

Congessional district extended report
https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/GeoCongdistsXreport.html?&areaid=4105&x=0.25&l=2&n=eys&dbindex=12&popYear=2010&nav=stateS-congS

Urban area extended report
https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/GeoUrbansXreport.html?&areaid=20422&x=0.25&l=2&n=eys&dbindex=12&popYear=2010&geotype=-1&geoid=null&nav=stateS-urbanS

Aggregated urban area extended report
https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/GeoUrbansRXreport.html?&popMin=0&popMax=2000000&x=0.25&l=2&n=eys&dbindex=12&popYear=2010&nav=stateS-AggUAS

Transit region extended report
https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/GeoRegionsXreport.html?&areaid=2a&x=0.25&l=2&n=eys&dbindex=12&popYear=2010&nav=stateS-regionS

**Comment by ODOT-RPTD-mb** [comment]
Add functionality to data dump reports.
