### ISSUE TITLE
Urban and Rural Stops?

### ISSUE THREAD

**Issue by PPaulsonOregonDOT** [ODOT-PTS/TNExT#171]
I was running a series of stop reports, from the Transit Regions Summary Report, which categorizes its stops at urban or rural.

https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/GeoRegionsReport.html?&dbindex=13&popYear=2010#

When I ran the urban and rural stops reports for region 2a, the same stop (stop number 14540, is the first stop listed in both reports for me) shows up in both urban and rural stop reports. Unless it is within a defined buffer distance of a urban/rural divide, I'm not sure how this is possible.

Region 2a Urban Stops Report:
https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/stopreport.html?&areaid=2a&type=4&x=0.25&n=ayt&dbindex=13&rc=0&popYear=2010&geotype=-1&stime=16:00&etime=19:00&geoid=null&nav=stateS-regionS

Region 2a Rural Stops Report:
https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/stopreport.html?&areaid=2a&type=4&x=0.25&n=ayt&dbindex=13&popYear=2010&rc=1&geotype=-1&geoid=null&stime=16:00&etime=19:00&nav=stateS-regionS

**Comment by PPaulsonOregonDOT** [comment]
I compiled the full list of urban and rural stops from these reports state wide, and the final list had 1,405 stops in it. the statewide for the September 2018 database. When I removed stop ID, agency ID duplicates, that number was reduced to 1,318, which is the number reflected in the statewide summary report. This suggests that 87 stops are being counted as both urban and rural, or are being counted as existing in more than one transit region. I was able to resolve the issue knowing that it existed, but it suggests that there is some type of geographic mismatch happening, which is likely effecting other reports.

@irees @drewda, given your understanding of the tool, could this same issue be causing some of the issues that we have noted in #24 and other urban/rural mismatches?

**Comment by anniekfifer** [comment]
@PPaulsonOregonDOT I've updated staging with a fix for this issue. It looked like the Urban Stops report wasn't being queried properly -- it was actually calling a query for all stops, not just urban. Note how the number of urban stops here is 744 but in the urban stops report there are 1,231 stops:
https://oregon.tnext.io/TNAtoolAPI-Webapp/GeoRegionsReport.html?&dbindex=13&popYear=2010#
https://oregon.tnext.io/TNAtoolAPI-Webapp/stopreport.html?&areaid=2a&type=4&x=0.25&n=ayt&dbindex=13&rc=0&popYear=2010&geotype=-1&stime=16:00&etime=19:00&geoid=null&nav=stateS-regionS

The total number of urban stops now match on staging:
https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/GeoRegionsReport.html?&dbindex=13&popYear=2010#
https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/stopreport.html?&areaid=2a&type=4&x=0.25&n=hpt&dbindex=13&rc=0&popYear=2010&geotype=-1&stime=0:00&etime=23:59&geoid=null&nav=stateS-regionS

Can you confirm if this looks correct? Thanks!

**Comment by PPaulsonOregonDOT** [comment]
@anniekfifer The fix you implemented in the staging version of the tool looks good.
