### ISSUE TITLE
Loss of 6 Agencies in Janaury 2019 Database

### ISSUE THREAD

**Issue by PPaulsonOregonDOT** [ODOT-PTS/TNExT#175]
There were 70 agencies recorded in the Sept 2018 Database OTA floatingdialog box, but only 64 show up for the January 2019 database, Attached is an excel sheet summarizing the differences. The actual differences in the snapshots represented by the the excel sheet I believe shows 7 agencies that are not matched up but the database numbers only show a difference of 6.
[TNEXT Database ComparisonSept19_Jan2019.xlsx](https://github.com/ODOT-PTS/TNExT/files/2809493/TNEXT.Database.ComparisonSept19_Jan2019.xlsx)

**Comment by PPaulsonOregonDOT** [comment]
EDIT to this issue:

These changes occurred in the OTA floating dialog box. All but Cog Wild, Mt. Bachelor, and Bandon City Trolley show up in the Transit Agencies Summary report for both January 2019 and Sept 2018 databases.

Cog Wild and Mt. Bachelor are lost as agencies in the January 2019 database, and their loss explains the reduction in the number of feeds from 60 in the Sept 2018 snapshot to 58 in the January 2019 snapshot Through inclusion in the Coos County GTFS feed, the 2019 snapshot picks up the Bandon City Trolley, which wasn't in the Sept 2018 database and doesn't appear in either OTA floating dialog.

In terms of feeds, I just downloaded the most recent set of GTFS feeds, and Mt. Bachelor's feed shows up in the list of available feeds, which raises the question of why it wasn't included in the January 2019 snapshot. Tagging @KalonThomas and @ODOT-RPTD-mb for insight into whether the loss of Mt. Bachelor and Cog Wild reflect a change in the state transit network, or in the availability of data for these two agencies.

**Comment by KalonThomas** [comment]
@PPaulsonOregonDOT -- It looks like an issue on my end. I'll make adjustments to add these Mt Bachelor and Cog Wild to the 2019 database. 

Just a note that there is a very high probability that the Mt. Bachelor Shuttle will be operating again in summer 2019 but we haven't received 100% confirmation. Therefore, the data for this agency will reflective of 2018 service levels extended into 2019.

**Comment by ODOT-RPTD-mb** [comment]
Valley Retriever, which has not operated for a few years shows up on OTA floating dialog box.
