### ISSUE TITLE
Data Dump Future population years

### ISSUE THREAD

**Issue by ODOT-RPTD-mb** [ODOT-PTS/TNExT#176]
Data Dump Report in both staging and production:
Parameters:
  Report Type: Counties
  Pop./Emp. Source: Values larger than 2010
  GTFS Source: September 2018
  Radius: 0.25
  Min Level of Service: 2
  Days: 1 September 2018

Report seems to stall at 1%, other data dump report types tested; i.e. Agencies, have the same symptom.

**Comment by irees** [comment]
https://github.com/ODOT-PTS/TNExT/blob/master/TNAtoolAPI-Webapp/src/main/webapp/resources/js/Datadump.js#L191
