### ISSUE TITLE
Urban and Rural Population Served at Level of Service in Agency Data Dump

### ISSUE THREAD

**Issue by PPaulsonOregonDOT** [ODOT-PTS/TNExT#181]
In the agencies Data Dump Report, there is a Urban/Rural Population Served recorded for each service. However, the Urban/Rural Population Served by Service, which is frequency weighted, shows a result of undefined. This report shows urban and rural service stops, the tool can recognize that there is service, but that is not being translated to the population served by service.

**Comment by PPaulsonOregonDOT** [comment]
https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/Datadump.html?&n=eDt&dbindex=15&popYear=2010

**Comment by anniekfifer** [comment]
[Agencies_Extended_Reports_Dump (1).txt](https://github.com/ODOT-PTS/TNExT/files/3633478/Agencies_Extended_Reports_Dump.1.txt)

**Comment by anniekfifer** [comment]
@PPaulsonOregonDOT The report above that I took from the url you posted gave me undefined values for urban and rural "Populations Served at Level of Service," not "Served by Service". Is that not what you were seeing earlier?

**Comment by anniekfifer** [comment]
For my own reference:

Urban/Rural population served at level of service:
>Total unduplicated population of urban/rural census blocks whose centroids are located within an X-mile radius of any stop of the transit agency and served at least N-times on the selected date(s). X is the population search radius and N is the minimum level of service set by the user.

Urban/Rural population served by service: 
>Summation of Population Served by Service over all urban/rural census blocks whose centroids are located within an X-mile radius (i.e., stop distance) of any stop served by the transit agency. Population served by service for a census block is calculated as the population of that block multiplied by the times the block is served by the transit agency on the selected date(s). The number reported is cumulative over the selected dates.

**Comment by anniekfifer** [comment]
>@PPaulsonOregonDOT The report above that I took from the url you posted gave me undefined values for urban and rural "Populations Served at Level of Service," not "Served by Service". Is that not what you were seeing earlier?

Oh right the url doesn't include the populated form parameters, do you have an example of a set of parameters that you used for the data dump to get undefined "Served by Service" values? I'll update my post above with the parameters I used

**Comment by PPaulsonOregonDOT** [comment]
@anniekfifer, you are correct that the undefined values are Urban and Rural Population served at "Level of Service."

**Comment by anniekfifer** [comment]
>@anniekfifer, you are correct that the undefined values are Urban and Rural Population served at "Level of Service."

But that isn't the problem for this issue, but that "... Served by service" is undefined? If so I'm having trouble reproducing that

**Comment by ODOT-RPTD-mb** [comment]
#209, Turned off TriMet feed, after delay (could've been 40+ minutes) ran agency data dump report, staging. TNExT indicated 54 of 55 feeds selected. Report included Trimet and undefined fields as indicated in earlier comments. Checked feed filter list trimet unchecked. Then un-selected ltd too, and saved filter changes, immediately ran agency data dump report, resulting in no Trimet and no ltd, and same undefined column values.... Is this expected feed filter behavior?

**Comment by thomastrillium** [comment]
> Is this expected feed filter behavior?

@ODOT-RPTD-mb will review and answer this question

**Comment by ODOT-RPTD-mb** [comment]
Deleted question. Inclusion of TriMet when filtered out is not appropriate behavior.

**Comment by anniekfifer** [comment]
I think this comment was meant for this issue: https://github.com/ODOT-PTS/TNExT/issues/209#issuecomment-553186498

**Comment by anniekfifer** [comment]
>Turned off TriMet feed, after delay (could've been 40+ minutes) ran agency data dump report

If it was over 40 minutes, this is expected behavior although it could be done in a less confusing way. I'll open an issue for discussing how to deal with terminated sessions

**Comment by ODOT-RPTD-mb** [comment]
Data dump default values, march 2019 db, 30 May, report completed, inside ODOT, remoting in to desktop.

Data dump default values, march 2020, 11 March, report completed inside ODOT, remoting in to desktop. Why does this report complete internal to ODOT while Title VI report does not. Pop served by service both rural and urban show as undefined.

[Agencies_Extended_Reports_Dump_Mar-2020_11-Mar.xlsx](https://github.com/ODOT-PTS/TNExT/files/4564794/Agencies_Extended_Reports_Dump_Mar-2020_11-Mar.xlsx)

Pop served by service is about census block internal point proximity to a transit stop. If block internal point is within specified radius of a transit stop then all block pop is counted as "served by service" pop is NOT double counted.

**Comment by philip-paulson-ibigroup** [comment]
I ran the Agency Level Data Dumps for July 2019 v2, December 2019, and March 2020 snapshots as part of testing the two new snapshots, and I've attached the 3 agency data dumps, don't seem to have any undefined values for any of the snapshots.

[December 2019 Agencies_Extended_Reports_Dump.xlsx](https://github.com/ODOT-PTS/TNExT/files/4738807/December.2019.Agencies_Extended_Reports_Dump.xlsx)
[March 2020 Agencies_Extended_Reports_Dump.xlsx](https://github.com/ODOT-PTS/TNExT/files/4738812/March.2020.Agencies_Extended_Reports_Dump.xlsx)
[July 2019 Agencies_Extended_Reports_Dump.xlsx](https://github.com/ODOT-PTS/TNExT/files/4738816/July.2019.Agencies_Extended_Reports_Dump.xlsx)
