### ISSUE TITLE
Timing Connection Report

### ISSUE THREAD

**Issue by PPaulsonOregonDOT** [ODOT-PTS/TNExT#182]
Neither the Linn Benton Loop or Tillamook County Transit services show any timing connections in the Timing Connections report, even when expanding the time parameter to over 3 hours. Many other agencies had reports that showed the expected results, including other agencies contained in the same GTFS feed as the problematic agencies, which suggests that there is an issue with how the schedule data for feeds with more than one agency are being processed.

**Comment by PPaulsonOregonDOT** [comment]
Portland Streetcar is showing the same behavior as above.

**Comment by PPaulsonOregonDOT** [comment]
It looks like the timing connections report starts having issues with these feeds at different snapshots, though I haven't been able to discern a pattern yet. I will post below the data information I'm able to uncover below, edited as I get more information:

Tillamook County Portland Connector: 
Expected Behavior: May 2017 DB, 5/17/2017
New Behavior: September 2017 DB, 9/20/2017

Sunset Empire
Expected Behavior: 
New Behavior:

**Comment by ODOT-RPTD-mb** [comment]
Seems to be fixed, perhaps with fix of multiple agencies in single feed issue.

**Comment by ODOT-RPTD-sh** [comment]
WOW!  There are only 19 open issues now…  Thanks so much.
