### ISSUE TITLE
Greyhound and Southwest POINT On-Map Behavior

### ISSUE THREAD

**Issue by PPaulsonOregonDOT** [ODOT-PTS/TNExT#187]
When selecting areas in and around Grants Pass, on-map reports for the last week using the March 2019 DB don't show the Southwest POINT or Greyhound service. If you select Greyhound from the floating bar, a stop is displayed just to the SE of grants pass, within the range of the circle I selected.

In checking the Census Place Extended Report for Grants Pass, it appears that all four of the agencies that I would expect to be represented show up.

https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/GASReport.html?&areaid=4130550&type=2&dbindex=15&popYear=2010&geotype=-1&geoid=null&nav=stateS-placeS

I checked previous snapshots of the network, and sometimes Southwest POINT shows up on the on-map report around Grants Pass but I haven't found a database/date combination that shows Greyhound. This suggests that the error observed above in the on-map report is related to how Greyhound's service is represented in the GTFS. I downloaded a new GTFS snapshot from the site, but as far as I can tell, greyhound's feed wasn't included, so I have no way to check the feed against the behavior that I've observed.

**Comment by PPaulsonOregonDOT** [comment]
I have discovered new behavior related to this issue. The stop near Grants Pass doesn't show up on the on-map report, but if you expand the circle slightly, both stops around Medford show up, which suggests that there is something specifically happening with the Grants Pass stop that isn't happening with other stops on that trip. I checked the GTFS data for the grants pass stop, and it is associated with 7 stop times and seven different trips, so the tool behavior that is causing this error is opaque to me.

**Comment by PPaulsonOregonDOT** [comment]
Similar behavior has developed with Klamath Shuttle around the Crate Lake area, in both staging and production versions of the tool, and across a wide range of database instances. It is possible that there is some odd behavior in this seasonal feed that is causing this behavior but the reports were generated for dates for the transit service was projected to be valid and active.

**Comment by anniekfifer** [comment]
This is caused by the query mistaken filtering out stops that are not within a .1 mile radius from a census block location from the results
