### ISSUE TITLE
City of Bandon Trolley

### ISSUE THREAD

**Issue by PPaulsonOregonDOT** [ODOT-PTS/TNExT#195]
The CIty of Bandon Trolley does not appear in the Transit Agencies list for the July 2019 database: https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/AgenSReport.html?&dbindex=16&popYear=2010 but it continues to show up as in the Connected Network Report:
https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/ConNetSReport.html?&gap=0.1&dbindex=16&popYear=2010

and connected agencies report
https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/ConAgenSReport.html?&gap=0.1&dbindex=16&popYear=2010

**Comment by evantrillium** [comment]
@PPaulsonOregonDOT - it is currently under the feed cooscounty-or-us

**Comment by PPaulsonOregonDOT** [comment]
I was able to locate it in the coos county feed. My concern is that within TNExT it shows up as an existing agency in some reports, noted above, but not in others. The most confusing and problematic omission I've discovered to this point is that it doesn't show up in the transit agency summary report:

https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/AgenSReport.html?&dbindex=16&popYear=2010#

and the statewide summary report
https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/GeoStateSreport.html?&dbindex=16&popYear=2010

The fundamental concern is that in some reports, it appears that there are 65 agencies loaded into the tool, and in others, there are 66.

**Comment by PPaulsonOregonDOT** [comment]
In examining the coos county feed, I noticed that City of Bandon Trolley is listed in agency.txt and routes.txt, but as far as I can tell, there aren't any trips in trips.txt that correspond to that route. This reflects reality, but would cause the City of Bandon of Trolley to have an "invalid" feed because there's no way to link stop times or stop times back to the agency in the relational database, and that the agency/on map reports exclude any agencies with 0 stops, trips or stoptimes, which we want to have happen, because if a feed's relational structure is broken, we don't want it being reflected in the tool. This sparked a theory:

1. The connectivity measures (Connected Agency and Connected Network reports), might simply compile a list of all of the agencies from all of the agency.txt files regardless of whether they have feeds that maintain relational integrity through the feed and then tries to uses the stop locations to determine whether stop connections exist.

This hypothesis is support by comparing the connectivity report for the March 2019 and July 2019 databases with a connectivity distance of 1 mile:

In March 2019, with that connection distance, the entire state is one network, including the City of Bandon Trolley.
https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/ConNetSReport.html?&gap=1&dbindex=15&popYear=2010#

 With the connection to the Trolley being provided by Curry County.

https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/ConAgenXReport.html?&gap=1&agency=980&dbindex=15

Using the July 2019 snapshot, even at one mile, the City of Bandon Trolley is part of its own network.

https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/ConNetSReport.html?&gap=1&dbindex=16&popYear=2010#

I checked the Curry County stop, and it hasn't moved, so the state should be one complete network at this connection distance, 

**UNLESS** the tool compiles found the City of Bandon Trolley as an agency, went to associate a collection of stops with that agency in order to determine the the spatial connections, but couldn't find any because they don't exist or can't be connected to the agency because there are no trip_ID's for that agency, and the tool returns zero spatial connections for that agency, which is what happens using the July 2019 database.

https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/ConAgenXReport.html?&gap=1&agency=980&dbindex=16

A fairly straightforward solution to this problem would be to remove from agency.txt any agencies that don't have service, either in the GTFS upload( and potentially write a verification protocol to return an error if a feed is not valid in this way).

**Comment by evantrillium** [comment]
Gotcha - Since we did not have service dates for that route this year, it was not assigned trips.

We are able to generate a GTFS with certain agencies removed (such as the trolley) - I can incorporate that into the review process prior to posting feeds to TNExT to ensure only agencies with active service in calendars.txt are included.

**Comment by PPaulsonOregonDOT** [comment]
This issue appears to be fixed in the July 2019 V2 database, and I will talk to the team about pushing it to production. 

An interesting note that might point to the underlying functionality that caused this issue, is that in the Statewide Summary Report, removing the Bandon trolley didn't change the number of transit stops in the state ((12,466 in each), This suggests that this report didn't even register that the trolley was a valid agency in the July 2019 feed, because removing its feed didn't effect the results.
