### ISSUE TITLE
Running TNExT locally for development

### ISSUE THREAD

**Issue by anniekfifer** [ODOT-PTS/TNExT#196]
Hi @irees @drewda 

I'm working on getting TNExT running on my machine but I'm not very familiar with war files or how they are deployed with docker. 

I'm experimenting with some updates to the dockerfile on my own branch annie-docker, currently it looks like `docker-compose up` starts everything up ok but nothing is served at port 8080. Any idea why or steps I may be missing? Can post docker logs if desired. 

Also, is docker the preferred setup for tnext development? I'd like to use it if is it but I'm not sure what the development loop is like with this type of docker setup.

**Comment by anniekfifer** [comment]
@ed-g helped me with the port issue -- I was looking at 8080 but docker assigns a port randomly unless its configured. There are several 500 errors on load to resolve however

**Comment by anniekfifer** [comment]
>There are several 500 errors on load at TNAtoolAPI-Webapp/ to resolve however

This exception is being thrown for these requests:

```
Type Exception Report

Message Servlet execution threw an exception

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

javax.servlet.ServletException: Servlet execution threw an exception
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
Root Cause

java.lang.NoClassDefFoundError: Could not initialize class com.webapp.api.Queries
	java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	com.sun.jersey.server.spi.component.ResourceComponentConstructor._construct(ResourceComponentConstructor.java:193)
	com.sun.jersey.server.spi.component.ResourceComponentConstructor.construct(ResourceComponentConstructor.java:182)
	com.sun.jersey.server.impl.resource.PerRequestFactory$PerRequest._getInstance(PerRequestFactory.java:182)
	com.sun.jersey.server.impl.resource.PerRequestFactory$AbstractPerRequest.getInstance(PerRequestFactory.java:144)
	com.sun.jersey.server.impl.application.WebApplicationContext.getResource(WebApplicationContext.java:225)
	com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:69)
	com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:136)
	com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:74)
	com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1347)
	com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1279)
	com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1229)
	com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1219)
	com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:419)
	com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537)
	com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:699)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
```

**Comment by anniekfifer** [comment]
I'm guessing the port needs to be 8080 so those requests can be listened for

**Comment by irees** [comment]
@anniekfifer I use a few additional settings in `docker-compose.override.yaml`, which is layered on top of the basic `docker-compose.yaml`. I am building a new instance now and will add my override file to your branch.

**Comment by irees** [comment]
Bootstrapping a new tnext instance is also greatly aided by importing an existing database snapshot and specifying it in the dbInfo.csv config file. I am testing now and adding instructions.

**Comment by irees** [comment]
hi @anniekfifer I created a new PR with some improvements to help get off the ground with a new installation, starting from a database export/snapshot.

https://github.com/ODOT-PTS/TNExT/pull/197/files 

Take a look at my changes to the Dockerfile (should be good out of the box without requiring docker-compose overrides). Also additions to the README for importing an initial database snapshot and creating a `dbInfo.csv` config file (tnext works better if at least one existing database is present).

**Comment by anniekfifer** [comment]
@irees This is great, thank you so much for putting that together!

It looks like it's mostly working but I'm not able to find the table "user_selected_agencies" in either the spring16 or winter16 databases. Other tables were installed fine and it doesn't look like pg_restore attempts to create the table so it's probably just missing. Is it possible that I need a more recent backup of the database and if so could you provide me with one?

**Comment by anniekfifer** [comment]
>Is it possible that I need a more recent backup of the database and if so could you provide me with one?

@irees pinging, it does look like I need a newer version of the database to run, let me know if that's not the case. Thank you!

**Comment by anniekfifer** [comment]
>@irees pinging, it does look like I need a newer version of the database to run, let me know if that's not the case. Thank you!

Found newer backups on my copy of the tnext server, closing for now.
