### ISSUE TITLE
State code in  key transit hubs and transit hubs report.

### ISSUE THREAD

**Issue by ed-g** [ODOT-PTS/TNExT#20]
Add STATE code “OR”, “WA”, “CA”, etc. to transit hubs in key transit hubs and transit hubs report.
There may be other non-geographic reports where state information could be useful.

**Comment by pouyalireza** [comment]
At present stops outside oregon are not associated with a state id.We are working on a solution to classify stops outside oregon.Any suggestions would be helpful.

**Comment by PPaulsonOregonDOT** [comment]
On the server side, I think you might be able to create state boundary files with the bare minimum data in it (ID, and STATE), and then spatially join then using a JOIN.... ON ST_Intersects(geom.Stops, geom.States) to add the state to each stop file (using the data contained in stop.txt), and that would allow you to query and group by the state identifier in the reports that need it.

**Comment by ed-g** [comment]
Quick search found this:

https://community.jaspersoft.com/wiki/how-generate-map-data-postgis-or-shapefiles-use-reports

https://www.census.gov/cgi-bin/geo/shapefiles/index.php

Might be useful.

**Comment by ODOT-RPTD-mb** [comment]
It may not be practical to address this issue by putting in place the infrastructure to support a fully multi-state TNA tool, but it is practical to take a step in that direction as part of making this change, that could be a plus.

**Comment by ed-g** [comment]
4-6 hours for first step here.
