### ISSUE TITLE
Extra Urban Stops in Reports

### ISSUE THREAD

**Issue by PPaulsonOregonDOT** [ODOT-PTS/TNExT#200]
In testing Congressional District reports from the July 2019 (and March 2019 Database), I have noticed that the number of stops listed in the urban stops field of the Congressional District summary report does not match number of entries in the stops summary report that can be reached using the corresponding hyperlink. Notice that Congressional District 1

https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/GeoCongDistsReport.html?&dbindex=16&popYear=2010#
 
shows 2,406 urban stops, but that the summary report below shows 2,717 entries

https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/stopreport.html?&areaid=4101&type=5&x=0.25&n=hnt&dbindex=16&popYear=2010&rc=0&geotype=-1&geoid=null&stime=0:00&etime=23:59&nav=stateS-congS

This behavior also appears in the Transit Region Report, which provides another data point for Issue #171 and confirmation of Issue #164

**Comment by anniekfifer** [comment]
Closing since I'm fairly sure this has been resolved with #171, the reports above both show 2,406 urban stops
