### ISSUE TITLE
data dump stall with seven days selected

### ISSUE THREAD

**Issue by ODOT-RPTD-mb** [ODOT-PTS/TNExT#205]
Data Dump Report not completing with seven days selected. In this particular example (Agencies/rad .25/ m-freq 2) with March 24th -March 30th selected report seemed to stall out at 97% on progress bar.
https://oregon.tnext.io/TNAtoolAPI-Webapp/Datadump.html?&n=hut&dbindex=14&popYear=2010

**Comment by PPaulsonOregonDOT** [comment]
This issue appears to be user dependent and intermittent (at least for me), but appears prevalent and problematic enough that we may want to consider an approach suggested by OSU whereby the tool sends pieces of data back and forth to prevent a browser/network from timing out.

 I think documentation should include a direction to users on a firewall/secured network to pull reports while off the network and for all users to only run one report at a time, which tends to bog down browsers.

**Comment by anniekfifer** [comment]
>Data Dump Report not completing with seven days selected. In this particular example (Agencies/rad .25/ m-freq 2) with March 24th -March 30th selected report seemed to stall out at 97% on progress bar.

I haven't been able to get this to completely time out. This report queries one agency at a time, and slows down for me also at 97% when trimet is queried for. 

it seems like it stalls sometimes, but if I go to another tab and return to the report it appears to complete the query. This may be a total coincidence that this has happened the handful of times I've tried it but it doesn't. 

I've experienced that on both staging and local, doing reports for both all agencies and just trimet on the "Slow 3G" chrome setting, usually selecting as many as 30-50 days

**Comment by anniekfifer** [comment]
>it seems like it stalls sometimes, but if I go to another tab and return to the report it appears to complete the query. This may be a total coincidence that this has happened the handful of times I've tried it but it doesn't.

I think this is a coincidence, or at least this isn't necessary for me to complete the report when it slows down on trimet.

**Comment by thomastrillium** [comment]
@ODOT-RPTD-mb or @ODOT-RPTD-sh will test at home to confirm this is an issue from home networks, or whether it is only an issue on ODOT network

**Comment by ODOT-RPTD-mb** [comment]
Tested outside of ODOT, report completed in ~14 minutes march 2020 db, default values, 8-mar -> 14-mar. Issue 180 still showing up.

**Comment by anniekfifer** [comment]
>Tested outside of ODOT - staging, report completed in ~14 minutes march 2020 db, default values, 8-mar -> 14-mar. Issue #181 still showing up.

Is the presence of #181 the only thing keeping this issue from being closed? Or are we keeping it open until we've confirmed that it's fixed inside the ODOT network?

**Comment by ODOT-RPTD-mb** [comment]
Keeping open due to inside ODOT issue.

**Comment by ODOT-RPTD-mb** [comment]
completed internal to ODOT.
