### ISSUE TITLE
Production upgrade

### ISSUE THREAD

**Issue by anniekfifer** [ODOT-PTS/TNExT#207]
I'm hoping to push fixes for #171 and #204 soon but just saw that there are a lot of other changes in master that haven't yet been pulled into production. 

@irees Can you or someone who may know confirm if it's ok for me to update production with these changes? I'll plan to hold off until I get the go-ahead. https://github.com/ODOT-PTS/TNExT/compare/production...master?expand=1

**Comment by anniekfifer** [comment]
I'll test a cherry-picked version without these changes today and upgrade with that after 5pm if all goes well

**Comment by anniekfifer** [comment]
@irees Can you confirm if there your commits here include that shouldn't be pushed to production without reviewing? I'm not sure whether or not tnext's master branch is intended to be clean/stable.

https://github.com/ODOT-PTS/TNExT/compare/production...master?expand=1

**Comment by irees** [comment]
@anniekfifer The master branch is intended to be stable enough for the development/staging environment. The production branch is for the production environment. 

I looked at the changes in the proposed production merge. The largest change is #170 which adds a "defaultDate" field to the config, which adds a "best service week" value to the list of agencies on the main map page, and a tool on the admin page to automatically select a best date for a database. It does not require a migration, and the field is optional in the dbInfo.csv config. I checked this just now.

You may also want to merge #197 which includes a Dockerfile with an updated base Ubuntu image. The Ubuntu 17:10 image used previously is no longer supported and will fail when trying to create a new build.
