### ISSUE TITLE
Extended Urban Area Report Pop Served vs Served at Level of Service

### ISSUE THREAD

**Issue by ODOT-RPTD-mb** [ODOT-PTS/TNExT#213]
![image](https://user-images.githubusercontent.com/8129162/68056646-e81a6b80-fcb0-11e9-96fa-aa135ced7a20.png)

![image](https://user-images.githubusercontent.com/8129162/68056697-04b6a380-fcb1-11e9-83ca-0c17543be38b.png)

https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/GeoUrbansXreport.html?&areaid=71317&x=0.25&l=2&n=hgt&dbindex=22&popYear=2010&geotype=-1&geoid=null&nav=stateS-urbanS

Urban pop served = 1,072,956
Urban pop served at level of service (2) = 1,072,969

Does this represent a field label mismatch? Would expect pop served to be larger or equal to pop served at level of service (2)?

https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/GeoUrbansXreport.html?&areaid=71317&x=0.25&l=16&n=hgt&dbindex=22&popYear=2010&geotype=-1&geoid=null&nav=stateS-urbanS

Hmmm, when bumping level of service value to (16) urban pop served at level of service drops to 966,252, which looks appropriate-ish, while urban pop served is unchanged at 1,072,956

**Comment by ODOT-RPTD-mb** [comment]
https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/GeoUrbansXreport.html?&areaid=71317&x=0.25&l=2&n=adr&dbindex=6&popYear=2010&geotype=-1&geoid=null&nav=stateS-urbanS

Looking at winter 2017 (4 jan 2017), served is larger than served at level of service (2), which is the expected relationship.

**Comment by ODOT-RPTD-mb** [comment]
Urban Areas datadump report, also show urban areas where pop served is smaller than pop served at los 2+

![image](https://user-images.githubusercontent.com/8129162/70169134-0e9c3f80-167f-11ea-9e1a-158c9eef84f2.png)

![image](https://user-images.githubusercontent.com/8129162/70169365-82d6e300-167f-11ea-8fc5-193f4b0d9a1a.png)

**Comment by thomastrillium** [comment]
@anniekfifer will investigate and scope

**Comment by anniekfifer** [comment]
There was a small difference between how "served" and "served at level of service" was being calculated -- "served" restricted counted populations to those nearby stops INSIDE the queried area, and "served @ LOS" did not. So "served" pop only looks at stops inside the area, and "served @ LOS" doesn't care about where the stops are (as long as they're within radius). 

The description of LOS fields say that it considers stops "within the geographical area" so I'm going to make that correction to the LOS field. This doesn't change the numbers drastically as it affects a small number of people and stops -- for reference, UPop @ LOS in @ODOT-RPTD-mb's first example decreases from 1,072,969 to 1,072,835 with this fix.
