### ISSUE TITLE
Automated GitHub critical security  issue fix

### ISSUE THREAD

**Issue by ODOT-RPTD-mb** [ODOT-PTS/TNExT#219]
https://github.com/ODOT-PTS/TNExT/pull/216

Should we move forward with this fix?

**Comment by thomastrillium** [comment]
@anniekfifer will confirm whether anything is needed here

**Comment by anniekfifer** [comment]
updated pull: https://github.com/ODOT-PTS/TNExT/pull/221

**Comment by anniekfifer** [comment]
Taking the liberty of closing this issue to cleanup the sprint board -- if no issues have come up this is fine
