### ISSUE TITLE
Make user session termination (which resets agency selection) less confusing

### ISSUE THREAD

**Issue by anniekfifer** [ODOT-PTS/TNExT#224]
Brought to attention by @ODOT-RPTD-mb: https://github.com/ODOT-PTS/TNExT/issues/181#issuecomment-553184577

I think a good option might be to both:
- alert the user when the session has terminated and ask them to refresh their window (this would look like the alert that appears after submitting selected agencies)
- extend the timeout interval by a lot so that won't happen as frequently. It is currently 40 minutes but at this time I don't see the harm in making this closer to the length of a workday. Testing this would be necessary but would require a little extra effort (i.e., keeping tnext open overnight, perhaps and testing agency selection the next day)

@ODOT-RPTD-mb @ODOT-RPTD-sh Does this sound ok to you? Let me know if you have any feedback. Feel free to assign priority labels.

**Comment by ODOT-RPTD-mb** [comment]
I like the alert the user suggestion. It is less clear to me what the "right" session timing is.

**Comment by anniekfifer** [comment]
> alert the user when the session has terminated and ask them to refresh their window (this would look like the alert that appears after submitting selected agencies)

Unfortunately doing this was more complicated than I thought and I didn't have time. Instead I've adjusted the session to time out after 4 hours of inactivity -- after that it should automatically reset to have ALL agencies selected, and should show that in the selected agencies count upon the first page navigation after the session has timed out. I think this should cover most use cases, reports shouldn't take more than four hours I hope (if there are exceptions let me know and I can adjust).

**Comment by anniekfifer** [comment]
@ODOT-RPTD-mb @ODOT-RPTD-sh This issue has been on production for a while now -- have either of you noticed any undesirable/unexpected behavior with user sessions? i.e. Feed selection resetting after/during long reports or long breaks in a disruptive way. If not please close if the current behavior works for you.
