### ISSUE TITLE
Title VI Report: "0" values in "Served", "Served by Service" and population fields

### ISSUE THREAD

**Issue by anniekfifer** [ODOT-PTS/TNExT#226]
From @ODOT-RPTD-mb in https://github.com/ODOT-PTS/TNExT/issues/209#issuecomment-590083059:

> Attempted to get fully populated seven days of Title VI report by breaking into two reports then re-assembling pieces to get to a single complete report by counties. March 2019 db, April 28-29-30, May 1-2-3-4, .5 radius, 2 los, all title VI fields selected.
> 
> Used TNExT to identify 27 feeds with service in Clackamas, Multnomah, or Washington counties, turned off all other feeds. Results for Clackamas and Washington fully populated, but Multnomah includes many zero values (SLOS fields populated, but S and SS have zero values). Did not explore selecting smaller Title VI field sets.
> 
> 
> Area ID | Area Name | 18 to 64 years | 18 to 64 years -   S(1) | 18 to 64 years -   SLOS(1)(2)(3) | 18 to 64 years -   SS(1)(3) | 5 to 17 years | 5 to 17 years -   S(1) | 5 to 17 years -   SLOS(1)(2)(3) | 5 to 17 years -   SS(1)(3) | 65 and older | 65 and older -   S(1) | 65 and older -   SLOS(1)(2)(3) | 65 and older -   SS(1)(3) | With Disability | With Disability -   S(1) | With Disability -   SLOS(1)(2)(3) | With Disability -   SS(1)(3) | Without   Disability | Without   Disability - S(1) | Without   Disability - SLOS(1)(2)(3) | Without   Disability - SS(1)(3) | American Indian   or Alaska Native | American Indian   or Alaska Native - S(1) | American Indian   or Alaska Native - SLOS(1)(2)(3) | American Indian   or Alaska Native - SS(1)(3) | Asian | Asian - S(1) | Asian -   SLOS(1)(2)(3) | Asian - SS(1)(3) | Black or African   American | Black or African   American - S(1) | Black or African   American - SLOS(1)(2)(3) | Black or African   American - SS(1)(3) | Hispanic or   Latino | Hispanic or   Latino - S(1) | Hispanic or   Latino - SLOS(1)(2)(3) | Hispanic or   Latino - SS(1)(3) | Native Hawaiian   and Other Pacific Islander | Native Hawaiian   and Other Pacific Islander - S(1) | Native Hawaiian   and Other Pacific Islander - SLOS(1)(2)(3) | Native Hawaiian   and Other Pacific Islander - SS(1)(3) | Other Races | Other Races -   S(1) | Other Races -   SLOS(1)(2)(3) | Other Races -   SS(1)(3) | Two or More Races | Two or More Races   - S(1) | Two or More Races   - SLOS(1)(2)(3) | Two or More Races   - SS(1)(3) | White | White - S(1) | White -   SLOS(1)(2)(3) | White - SS(1)(3) | Asian &   Pacific Islander | Asian &   Pacific Islander - S(1) | Asian &   Pacific Islander - SLOS(1)(2)(3) | Asian &   Pacific Islander - SS(1)(3) | English | English - S(1) | English -   SLOS(1)(2)(3) | English -   SS(1)(3) | Indo European | Indo European -   S(1) | Indo European -   SLOS(1)(2)(3) | Indo European -   SS(1)(3) | Other Languages | Other Languages -   S(1) | Other Languages -   SLOS(1)(2)(3) | Other Languages -   SS(1)(3) | Spanish | Spanish - S(1) | Spanish -   SLOS(1)(2)(3) | Spanish -   SS(1)(3) | Above Poverty   Line | Above Poverty   Line - S(1) | Above Poverty   Line - SLOS(1)(2)(3) | Above Poverty   Line - SS(1)(3) | Below Poverty   Line | Below Poverty   Line - S(1) | Below Poverty   Line - SLOS(1)(2)(3) | Below Poverty   Line - SS(1)(3)
> -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
> 41051 | Multnomah County | 526,883 | 0 | 506,550 | 0 | 106,597 | 0 | 101,004 | 0 | 88,521 | 0 | 83,668 | 0 | 98,555 | 0 | 94,830 | 0 | 664,652 | 0 | 635,354 | 0 | 4,633 | 0 | 4,338 | 0 | 52,072 | 0 | 49,028 | 0 | 40,815 | 0 | 40,434 | 0 | 85,201 | 0 | 83,538 | 0 | 4,710 | 0 | 4,669 | 0 | 1,740 | 0 | 1,653 | 0 | 31,326 | 0 | 29,929 | 0 | 547,918 | 0 | 522,377 | 0 | 41,958 | 0 | 39,823 | 0 | 577,765 | 0 | 552,376 | 0 | 32,809 | 0 | 30,765 | 0 | 9,750 | 0 | 9,553 | 0 | 59,718 | 0 | 58,705 | 0 | 616,821 | 0 | 587,037 | 0 | 136,471 | 0 | 134,043 | 0
> 
> 
> Need fix for Transit Network Report.

And https://github.com/ODOT-PTS/TNExT/issues/209#issuecomment-622228687:

> Report completed for march 2020, 8th-14th March, .5 radius, Counties all title VI elements, outside of ODOT environment. But gaps in data... i.e. multiple instances of 0 population in 18-64 age range.
> 
> [Title VI Report (1).zip](https://github.com/ODOT-PTS/TNExT/files/4564599/Title.VI.Report.1.zip)
> 
> Report did not complete within ODOT after 3+ hours (remoting in to desktop).
> 
> Incomplete report more of an issue than ODOT environment completion failure.

**Comment by ODOT-RPTD-mb** [comment]
@anniekfifer  Outside of ODOT, March 2020 db (staging), default values for 1-April-2020. All fields selected. Completed in ~1 minute values look reasonable. Again with 1 April - 4 April selected. Completed in ~1 minute values look reasonable. Again 29 March - 4 April (7 days) selected. Completed in ~2 minutes, values look reasonable. Again but with .5 radius (29th-4th, 7 days). Completed in ~3 minutes, **many many inappropriate zero values.**

**Comment by philip-paulson-ibigroup** [comment]
I just ran this report as part of spot checking the March 2020 database using the parameters noted above, and the report took 3-5 minutes to complete, and provided the resulting data. This data looks reasonable to me.
[Title VI Report.zip](https://github.com/ODOT-PTS/TNExT/files/4738772/Title.VI.Report.zip)

**Comment by ODOT-RPTD-sh** [comment]
I am able to replicate the testing Phil did, in Production and Staging, without errors.
