### ISSUE TITLE
Timing Connection Report not representing multi-agency feeds correctly.

### ISSUE THREAD

**Issue by philip-paulson-ibigroup** [ODOT-PTS/TNExT#231]
When I selected Albany Transit  System’s Early Morning route in the Timing Connection report neither of the runs shows any   timing connection to other services. However, when I run the same report for  the Amtrak Cascades service(only changing the service, route, and run)  it shows a timing connection (21 minutes) with the Early Morning service at the Albany Amtrak station.  I have found that when you run a timing connections report for a connected agency(Amtrak   Cascades) and run(5:30 run) that would be expected to connect to that   service, those routes/stops show up as valid timing connections. This also appears to be the case with Basin Transit routes, as those routes don’t show   any connections from the timing connections report, but if you select a run of the Coast Starlight for the same day and time period, the Basin Transit services  show up as timing connections. 

This issue appears to be consistent across the December 2019 and March 2020 databases, and be limited to services that share a GTFS feed with another agency, with one agency in each feed showing the appropriate behavior. A great example of this is shown with the Albany GTFS feed, where Albany Transit and Lebanon Senior Center don't show any timing connections, but using the same settings(date, time parameters), selecting the 14:05 run of the Linn-Benton loop shows timing connections to an Albany Transit route, which doesn't show the same timing connection when selected.

**Comment by philip-paulson-ibigroup** [comment]
This appears to continue to be the case in both the June and December 2020 snapshots. @anniekfifer, has this change be deployed to the staging server at this point?

**Comment by anniekfifer** [comment]
@philip-paulson-ibigroup It has not, staging is scheduled to be updated with this fix by January 28
