### ISSUE TITLE
Employment Report Completing with Partial Dataset

### ISSUE THREAD

**Issue by philip-paulson-ibigroup** [ODOT-PTS/TNExT#233]
In testing the county level employment report, when a full week is selected, the population search parameter is set to .5 miles for and all data fields are selected, for both the March 2020 and December 2019 snapshots, the report completes, but only produces data for 16 of the 36 counties in Oregon. If the same parameters are used (1 week, .5 miles, all fields selected) for a week where some agency feeds would be expected to have expired, particularly agencies with large datasets, the report completes as expected. This suggests that the backend behavior observed in #140  may still be occurring, but that after a defined period of time, the tool generates an incomplete report with the data is has been able to compile to the user.
[Employment Report.zip](https://github.com/ODOT-PTS/TNExT/files/5125634/Employment.Report.zip)
[Employment Report Expired Feed.zip](https://github.com/ODOT-PTS/TNExT/files/5125689/Employment.Report.Expired.Feed.zip)

**Comment by anniekfifer** [comment]
Note to self - The index added for lodes_blocks_wac in #140 should probably be on the RAC table also, likely the cause of the query slowness

**Comment by ODOT-RPTD-mb** [comment]
Ran employment report for the week (7 days) ending dec 23rd 1 visit, WAC, .5 radius, counties, ( all or most feeds active for this period) see 16 counties in result rather than the full (36?) (staging - within ODOT environment)

**Comment by anniekfifer** [comment]
@ODOT-RPTD-sh or Frank -- Could one of you attempt running the employment report on production TNEXT (and in the ODOT environment) with the parameters above and let me know if you also get partial results? I'm not able to reproduce this on my end.

**Comment by ODOT-RPTD-sh** [comment]
Dec 2020 Production snapshot, tested on ODOT network - completed quickly and with all counties (took less than 5 min)
