### ISSUE TITLE
Discrepancy in service miles when joining against two geographies

### ISSUE THREAD

**Issue by anniekfifer** [ODOT-PTS/TNExT#235]
Happens in the same situation but is a separate problem from #164 

https://oregon.tnext.io/TNAtoolAPI-Webapp/GeoUrbansXreport.html?&areaid=04654&x=0.25&l=2&n=gat&dbindex=15&popYear=2010&geotype=4&geoid=5&nav=stateS-regionS-urbanS

service miles-related fields should match the below report

https://oregon.tnext.io/TNAtoolAPI-Webapp/GeoUrbansXreport.html?&areaid=04654&x=0.25&l=2&n=gat&dbindex=15&popYear=2010&geotype=-1&geoid=null&nav=stateS-regionS-urbanS

It looks like intersecting the urban-bound trip segment with the county-bound trip segment might cut off a bit of the linestring somehow, despite the urban area being wholly inside the county, resulting in fewer service miles

**Comment by anniekfifer** [comment]
There are multiple issues at play that I'm going to try to illustrate the scope/severity of with an example:

This is the urban boundary for Baker City:

<img width="443" alt="Screen Shot 2020-11-23 at 5 41 04 PM" src="https://user-images.githubusercontent.com/20935033/100037078-4e8b9380-2db6-11eb-828b-6579e17633e1.png">

This is the path of a trip that travels along its border (it continues north):

<img width="296" alt="Screen Shot 2020-11-23 at 5 42 28 PM" src="https://user-images.githubusercontent.com/20935033/100037093-564b3800-2db6-11eb-9367-52cb14fcf1d6.png">

This is the segment of the trip TNEXT considers to be in Baker City:

<img width="443" alt="Screen Shot 2020-11-23 at 5 44 08 PM" src="https://user-images.githubusercontent.com/20935033/100037107-5ba88280-2db6-11eb-8738-9aaae5266629.png">

When calculating service miles, this the segment of the trip TNEXT considers to be in Baker City _and_ Baker County (although Baker City is entirely contained by Baker County):

<img width="406" alt="Screen Shot 2020-11-23 at 5 44 43 PM" src="https://user-images.githubusercontent.com/20935033/100037141-69f69e80-2db6-11eb-9151-0b9cc91cae08.png">

The two issues I see are separate problems:
1. Segmenting trips on both urban area and county is inaccurate, the last two trip segments above should look the same. 
    - This problem only affects service miles that filter on two geographies but is likely affecting any trip that crosses or travels along a geographical border.
2. Trips segments that travel along a geographical border are unpredictably "assigned" an area they belong to. In the example above, I would have expected that the segment that's considered to be inside Baker City would continue along the urban border on route 30, and that the same segment would also be counted as being in the urban area north of the border. The scope of this depends on what the desired behavior is:
    - From an analysis perspective, is it ok for trip segments to "belong" to multiple geographic areas?
    - If a change to this is needed, does it need to be applied retroactively to databases? Or is fixing for future snapshots sufficient?
    - If a trip is _only_ along the border of an area but isn't in the area otherwise, should TNEXT count that trip as being inside that area?

**Comment by ODOT-RPTD-sh** [comment]
#2.  Would it be possible to determine the number of service miles affected by the border issue?  (2 - 3 hours estimated?)  And, in this analysis, determine whether this unpredictability affects only a subset /trip segment on the border or the entire trip?  With this information, we can determine the best options, or whether, to request a fix.

**Comment by anniekfifer** [comment]
@ODOT-RPTD-sh Sorry for delayed response -- I've spent about 3 hours trying to run one of the queries for this analysis but it's quite computationally expensive. I had to take some time to get the query to finish at at all, and now that I have it working working it seems to take several hours and counting just to analyze trip miles along county borders.

I'm worried that this doesn't bode well for our options for this issue. The geographic analysis I'm trying to run in these queries (measuring trip shapes within several meters of the geographical border) is similar to what a solution for issue 2 would require. I can keep continuing with this analysis to get a clearer idea of how much this change this would increase snapshot creation time and to hopefully give you some information to work off of, but what I'm seeing now is that refining trip analysis along borders could likely add several hours to snapshot creation and may be prone to error.

**Comment by anniekfifer** [comment]
>Would it be possible to determine the number of service miles affected by the border issue?

@ODOT-RPTD-sh @ODOT-RPTD-mb Some good news, with a little more time I was able to get some numbers for you on this. The values below are the number of service miles that are within .01 miles (about 16 meters) of a border for the given geography type for one day. I ran these on Wednesday, March 18th on the March 2020 database -- I realized afterwards that this might not have been the best month to pull from but I'm thinking this is early enough to avoid major covid-related service changes, but let me know if you'd like me to check on that or want me to run on a different date.

Total service miles on March 18th 2020: 171757.71 miles

Counties: 356.80 miles along borders (.2% of total service miles)
Congressional Districts:  2220.23 miles along borders (1.3%)
Tracts : 4970.92 miles along borders (2.9%)
Urban Areas: 5790.63 miles along borders (3.4%)

**Comment by anniekfifer** [comment]
>Segmenting trips on both urban area and county is inaccurate, the last two trip segments above should look the same.
This problem only affects service miles that filter on two geographies but is likely affecting any trip that crosses or travels along a geographical border.

This fix is on master, will be included in the release. There's still a very small discrepancy -- in the Baker County/urban area example service miles are now 148.2062 filtering on baker county ("correct" value is 148.21) rather than 111.87695 -- and unfortunately I don't think it's possible to improve the accuracy beyond that
