### ISSUE TITLE
June 2020 OTA floating dialogue box

### ISSUE THREAD

**Issue by philip-paulson-ibigroup** [ODOT-PTS/TNExT#239]
For the June 2020 database, the OTA floating dialogue box does not reflect the agencies included in the data snapshot, most notably the Valley Retriever is included, which has been out of operation for 2+ years.

**Comment by anniekfifer** [comment]
Thanks @philip-paulson-ibigroup ! I didn't see this before opening #240, discussion for this will be continued there
