### ISSUE TITLE
Feed start and end date can go un-set if feed has no calendar.txt entries and no feed_info.txt entries

### ISSUE THREAD

**Issue by anniekfifer** [ODOT-PTS/TNExT#241]
Transit Agencies Summary report was failing because LTD had 'N/A' for its start and end date values -- tnext should update these fields during snapshot creation but that query fails to update if there are no calendar entries.

Known impact currently is just the Transit Agencies Summary report but it could likely affect other reports.

@ODOT-RPTD-mb @ODOT-RPTD-sh This is an easy fix (<1 hour), shall I include in the current sprint? This should be addressed before any new snapshots are created.

**Comment by ODOT-RPTD-sh** [comment]
Please include fix of this bug in current sprint; date of Dec 2020 snapshot will depend on issue resolution.

**Comment by anniekfifer** [comment]
@anniekfifer  to QA in July when new snapshot is pushed to staging
