### ISSUE TITLE
40+ Inactive stops in Wilsonville feed

### ISSUE THREAD

**Issue by ODOT-RPTD-mb** [ODOT-PTS/TNExT#248]
**Phil noted a large increase in stop count for wilsonville:**

_In terms of testing of the new snapshots, the data has generally looked reasonable in terms of changes between snapshots, with a few exceptions. From June 2020 to December 2020, 6 agencies showed increases in the number of stops of between 40% and 100%, and Woodburn's stop numbers rose from 7 to 53 stops, which is a significant increase._

**Looking at Woodburn (Agency-stops) a week (10th – 16th) in January 8 of 53 (Dec 2020 db)stops are visited 1 or more times, implying a bunch of stops in the feed that are not “active” [Action – ask Trillium to confirm assumptions]**

https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/stopreport.html?&agency=129&n=ajvakvalvamvanvaovapv&x=0.25&dbindex=32&popYear=2010&geotype=-1&geoid=null&areaid=null&type=null&route=null&nav=stateS-agencyS&rc=-1&stime=0:00&etime=23:59

**Comment by ODOT-RPTD-mb** [comment]
https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/GeoRegionsXreport.html?&areaid=4&x=0.25&l=1&n=afv&dbindex=32&popYear=2010&nav=stateS-regionS
Wed-6-Jan-2021, .25 radius, min level of service = 1

Region 4 extended report, percent pop served value = 28.7%, while percent pop served at level of service = 16.7% would expect these value to be much closer, unless there are many un-utilized stops in feed.

See similar (larger) variation for region 3, but values more as expected in region 2b.

This could be just a large variation in full stop profile across a week (or month) versus for a Wed.? 
Or, maybe large element of seasonal service?
Or, it could be many unused stop-relics in feeds?
Or, software issue that does not impact regions in the same way?

**Comment by ODOT-RPTD-mb** [comment]
Pop served versus pop served at level of service for region extended report above seems to be explained by expired feeds.

**Comment by anniekfifer** [comment]
This is accurate to the GTFS -- there is one active route for woodburn that serves those 8 stops. According to their website they have that route in service plus weekend service (stops/schedule for which I can't find). I've let trillium support know, they're looking into it but if ODOT is concerned about this feed for the Dec 2020 snapshot they may want to connect with Evan or Weston directly. Closing since this is not a TNEXT bug.

**Comment by anniekfifer** [comment]
>Closing since this is not a TNEXT bug.

But feel free to reopen if ODOT would like to keep track of the potential data issue here
