### ISSUE TITLE
Data Dump completion when not 'on screen'

### ISSUE THREAD

**Issue by ODOT-RPTD-sh** [ODOT-PTS/TNExT#255]
Phil discovered this issue when testing the June 15 2021 Staging snapshot, but I'm finding it is also occurring in the Production tool.  I also tested June15 2021, Dec 2020 and June 2020 in Production.

My testing was seven days and using two monitors.  When the report was running on a monitor and stayed visible (not minimized or with another application opened 'on top of it") the report completed in 8 - 12 minutes.  If the report running screen was not displayed (and as Phil found), it could take forever, really only completing once the user opens the report on their screen.  (At one point, when it wasn't displayed, the report stalled for about 3 minutes at 94%, the “want to continue or close?” warning displayed, and the report ultimately completed in just over 8m with the screen open/visible.) 

Have not been able to replicate this for any other type of report; others - in Staging and Production - are completing in a timely manner (displayed or not).

**Comment by anniekfifer** [comment]
reopening so ODOT can test and close

**Comment by ODOT-RPTD-sh** [comment]
Used June 2021 in Staging, 7 days, other defaults - took about 25 minutes, but progress did not seem affected by keeping the TNExT screen on top. Fix accomplished!
