### ISSUE TITLE
Cannot upload files >2MB

### ISSUE THREAD

**Issue by anniekfifer** [ODOT-PTS/TNExT#265]
This is blocker for snapshot creation, as LTD, RVTD and Trimet are all over 2MB.

The client_max_body_size setting in tnext.conf appears to be getting ignored suddenly, it's using the 2MB default value. When trying to upload one of the above feeds, the response returns a "413 Request Entity Too Large" error. I haven't been able to get any short-term fixes to work yet (e.g. adding the setting in other conf files directly)

I can't reproduce this locally, but can on tnext-b production and tnext staging. Things I've done/tried:
- Confirmed in the docker container that the tnext.conf is present in /etc/nginx/conf.d and that it's included in /etc/nginx/nginx.conf
- Added client_max_body_size to default.conf directly and restarted nginx from within the container
- Confirmed that client_max_body_size isn't being set elsewhere in the docker container or on tnext host nginx configs
- Changing the nginx image tag to the previous stable version rather than latest (1.20.2-alpine)
- Confirmed that client_max_body_size is being listened to locally -- if I change it to 2M I get the same error locally as on tnext staging
- Used debug mode (`command: [nginx-debug, '-g', 'daemon off;']`) hoping to see configuration-related errors, found nothing
- Confirmed that several things have not changed since last snapshot that could have caused this (dockerfile, docker-compose.yml, docker/docker-compose version, tnext.conf, etc.)

**Comment by anniekfifer** [comment]
This fix has been applied to production and staging, feed uploads are now working

**Comment by christrillium** [comment]
Woohoo!!!!
