### ISSUE TITLE
CSV file upload/import not working

### ISSUE THREAD

**Issue by anniekfifer** [ODOT-PTS/TNExT#276]
I discovered during my testing of Census data import importing of csv files during snapshot creation for employment, Title VI, park and ride, etc. is not working (note that GTFS file upload/import works fine, since it uses a different method to import table data). 

I'm not sure when this feature was last used, but my hunch is that it was broken during a postgres update a long time ago. The problem seems to be that postgres `COPY` expects to be able to import the csv file uploaded to the `tnext` container, when it really needs to be available on the database container for `COPY` to work. 

I've documented a workaround in this [readme](https://github.com/ODOT-PTS/TNExT/tree/master/census#d-import-additional-datasets) (which should be updated when this issue is fixed), but it's inelegant and it'd be tedious to perform on a remote TNExT deployment.

**Comment by ed-g** [comment]
Look to see if java postgresql library can COPY from a pipe.
