### ISSUE TITLE
Ensure that there are at least 7 contiguous days during which all feeds are valid

### ISSUE THREAD

**Issue by antrim** [ODOT-PTS/TNExT#4]
For each new GTFS dataset ensure that there are at least 7 contiguous days during which all feeds are valid (are between feed start and end dates) (feed can both be valid and have no service for period in question) [Trillium is the logical lead on this activity]
Possible tactics include:
* Attention to timing of GTFS feed capture
* Changes to Trillium start/end date feed practices
* Requests to non-Trillium feed producers to modify start/end practices
* Forced editing of valid feed range (not-so-desirable)
* Other…?

This is particularly useful for GTFS-ride. i.e. It is particularly useful to know if past service dates were valid.

**Comment by antrim** [comment]
@pouyalireza Can you close or delete this?

**Comment by BenFields724** [comment]
This task is addressed in the newly added feed duration visualizer.

**Comment by ODOT-RPTD-mb** [comment]
This is still a Trillium process issue. How does Trillium trigger a build so that looking back seven days all feeds are valid. We should consider this task complete, when we have a new db in place with 7+ days of contiguous validity, and Trillium understands the issues associated with making this happen. Speed is an issue for ODOT on this issue; we can use a "solid" snapshot of the network to build some report documents. This db build should include the P&R update.

**Comment by PPaulsonOregonDOT** [comment]
This may be obvious, but I think that because it needs another db build, this needs to be preceeded by an answer to #16 related to evaluating where the tool will be hosted moving forward. @BenFields724, @pouyalireza, do we have an answer to that question? I think that this may also require, us to not include services that don't run year round, because those significantly shrink our window. @ed-g, in looking at the overlap of service, it looks like  feed_end_date could be adjusted to extend this window, while keeping end_date in calendar.txt the same, which I would hope would allow those short term services to continue showing up correctly in google transit, etc.

**Comment by antrim** [comment]
Trillium should proceed "with an eye to an ongoing, perhaps quarterly build process by Trillium." (via M Barnes, @ODOT-RPTD-mb).

cc: @ed-g 

Can someone please assign this to @antrim or @ed-g ? I do not have access to make assignments on this repo.

**Comment by antrim** [comment]
cc: @thomastrillium

Here is what the Spec says about feed_info.feed_start_date and feed_info.feed_end_date:

> |  Field Name | Required | Details |
> |  ------ | ------ | ------ |
> |  feed_start_date | Optional | The feed provides complete and reliable schedule information for service in the period from the beginning of the **feed_start_date** day to the end of the **feed_end_date** day. Both days are given as dates in YYYYMMDD format as for [calendar.txt](#calendartxt), or left empty if unavailable. The **feed_end_date** date must not precede the **feed_start_date** date if both are given. Feed providers are encouraged to give schedule data outside this period to advise of likely future service, but feed consumers should treat it mindful of its non-authoritative status. If **feed_start_date** or **feed_end_date** extend beyond the active calendar dates defined in [calendar.txt](#calendartxt) and [calendar_dates.txt](#calendar_datestxt), the feed is making an explicit assertion that there is no service for dates within the **feed_start_date** or **feed_end_date** range but not included in the active calendar dates. |
> |  feed_end_date | Optional | (see above) |

(https://github.com/google/transit/blob/master/gtfs/spec/en/reference.md#feed_infotxt)

GTFS Best Practices says:
> One GTFS dataset should contain current and upcoming service (sometimes called a “merged” dataset). Google transitfeed tool's merge function can be used to create a merged dataset from two different GTFS feeds.
> - At any time, the published GTFS dataset should be valid for at least the next 7 days, and ideally for as long as the operator is confident that the schedule will continue to be operated.
> - If possible, the GTFS dataset should cover at least the next 30 days of service.

(http://gtfs.org/best-practices/#publishing_4)

Proposed next steps:

- [ ] **Look at TNA software and use case:** If the Spec and Best Practices are followed, does that give all the data that is necessary for this use case? If not, do we need to propose new data practices?
- [ ] **Look at Trillium data practices:** What are we providing in the way of feed_start_date and feed_end_date? Do we need to change anything?
- [ ] **Trillium changes data practices if necessary**: This might include changing our practices around feed_end_date. We could change practice around querying Oregon agencies for upcoming service changes…
- [ ] **Trillium changes data practices, if necessary** 
- [ ] **Trillium suggests that other (non-ODOT published GTFS) transit agencies should conform with practice, if necessary** 
- [ ] **We look at/for specific examples where it is not possible to get 7 contiguous days** and figure how how to make surgical or systematic changes/improvements.

**Comment by ed-g** [comment]
Needed for reporting document. Was hoping to have it in place by 15th! But in next week can survive that.

**Comment by ed-g** [comment]
* [ ] build a new db, "October 2017"
* [ ] import gtfs feeds to new db
* [ ] check for where gaps in 7 contiguous days exist, look for 3 candidates for 7 contiguous days
  * [ ] For each candidate try to find gtfs feeds of proper start/end dates to fill gap

**Comment by ed-g** [comment]
@ODOT-RPTD-mb @PPaulsonOregonDOT @srinivas13794 @BenFields724 are the GTFS feeds in the Tna tool loaded from the Public+Private gtfs archive site? If not, what is the process for fetching GTFS feeds?

**Comment by ODOT-RPTD-mb** [comment]
Yes, feeds are captured from private+public Trillium site.

**Comment by ed-g** [comment]
Uploading feeds from http://archive.oregon-gtfs.com/archive-download-private/Oregon-Private-GTFS-feeds-2017-09-18Z.zip (you'll need a login to access that URL).

**Comment by ed-g** [comment]
If we create a GIST index on census_blocks.shape, testing for contained points goes much faster.

```sql
create index census_blocks_shape_idx on census_blocks using gist (shape) ;
```

**Comment by ed-g** [comment]
This will enable parallel queries on the database which could speed things up depending on the exact query.

```sql
alter database september17 set max_parallel_workers_per_gather= 8;
```

**Comment by ed-g** [comment]
Pretty close, there are a couple agencies which are ruining the party. Klamath seems to have expired a couple years ago, and CCCXPRESS starts in the future.

```sql
september17=# select enddate::date, feedname from gtfs_feed_info order by enddate asc limit 10;
  enddate   |          feedname           
------------+-----------------------------
 2016-09-05 | klamathshuttle-or-us
 2017-10-31 | washingtonparkshuttle-or-us
 2017-12-02 | trimet-portland-or-us
 2017-12-06 | cccxpress-or-us
 2017-12-25 | valleyretriever-or-us
 2017-12-30 | salem-or-us
 2018-01-01 | cascadespoint-or-us
 2018-01-01 | albanytransit-or-us
 2018-01-01 | cooscounty-or-us
 2018-01-01 | amtrakcascades-or-us
(10 rows)


september17=# select startdate::date, feedname from gtfs_feed_info order by startdate desc limit 10;
 startdate  |          feedname           
------------+-----------------------------
 2017-09-25 | cccxpress-or-us
 2017-09-10 | ctran-wa-us
 2017-09-03 | salem-or-us
 2017-09-03 | trimet-portland-or-us
 2017-08-01 | northwestpoint-or-us
 2017-08-01 | pacifictransit-wa-us
 2017-06-18 | lanetransitdistrict-or-us
 2017-05-11 | highdesertpoint-or-us
 2017-04-01 | washingtonparkshuttle-or-us
 2017-02-01 | hut-or-us
(10 rows)
```

**Comment by ed-g** [comment]
CCCXpress from 14 September looks like it starts on the 13th. I wonder why tna tool thinks it starts on the 25th.

oregon-gtfs.com also shows it as starting on the 13th.

```
feed_publisher_url,feed_publisher_name,feed_lang,feed_version,feed_license,feed_contact_email,feed_contact_url,feed_start_date,feed_end_date
http://www.trilliumtransit.com,"Trillium Solutions, Inc.",en,UTC: 14-Sep-2017 00:38,,support+cccxpress-or-us@trilliumtransit.com,http://support.trilliumtransit.com,20170913,20171206
```

**Comment by ed-g** [comment]
Klamath Shuttle (aka Crater Lake Trolley) will run this year until October 10th or 11th.

**Comment by ed-g** [comment]
Protip: use application/json to fetch data from Daterange backend. Browser confuses the backend by asking for html and xml.

```bash
curl -H 'accept: application/json' http://tna.trilliumtransit.com:8080/TNAtoolAPI-Webapp/queries/transit/Daterange?dbindex=10
```

**Comment by ed-g** [comment]
@ODOT-RPTD-mb @PPaulsonOregonDOT it looks like there is a little over a month of contiguous validity (September 25th through October 31st), with the single exception of the Klamath shuttle which runs only seasonally and is done for the year.

Let me know if this gives you what you need for the report?

```sql
september17=# select enddate::date, feedname from gtfs_feed_info order by enddate asc limit 5;  select startdate::date, feedname from gtfs_feed_info order by startdate desc limit 5;
  enddate   |          feedname           
------------+-----------------------------
 2017-10-31 | washingtonparkshuttle-or-us
 2017-12-02 | trimet-portland-or-us
 2017-12-06 | cccxpress-or-us
 2017-12-25 | valleyretriever-or-us
 2017-12-30 | salem-or-us
(5 rows)

 startdate  |       feedname        
------------+-----------------------
 2018-07-01 | klamathshuttle-or-us
 2017-09-25 | cccxpress-or-us
 2017-09-10 | ctran-wa-us
 2017-09-03 | trimet-portland-or-us
 2017-09-03 | salem-or-us
(5 rows)
```

**Comment by ODOT-RPTD-mb** [comment]
Potentially this works for a short term fix. I would expect Columbia Gorge Express to show up (or not show up) in the same way that the Klamath Shuttle does in that it is also a seasonal summer service that is not currently operating?

For the longer term we probably want to: 
- Only consider contiguous time blocks in the past with respect to the capture date, when looking for 7 consecutive days to capture, because feed updates can happen at any time (see red circled text in table below). We might want to add data capture date to bottom of agency dropdown menu for context.
- Make sure that Trillium is using consistent and predictable methodology around service start-end dates
- Consider how to handle seasonal services like the Klamath Shuttle and Columbia Gorge Express in a way that does not mislead the end user re:  time periods while seasonal service is inactive equates to incomplete data for that time period.
- Consider how to detect/handle contradictions/inconsistencies between feed start/end date and calendar files. Is this already being tested for?
- Consider modifying text at bottom of agency list dropdown, or modifying data processes, so that it does not show a "no valid date range" message, when the only "expired" data is from out of season, seasonal service.

![image](https://user-images.githubusercontent.com/8129162/30571085-4ad47c76-9c9a-11e7-902b-b30e33e0a8e2.png)

**Comment by ed-g** [comment]
Sorry just a quick response for now

* Feed capture date is available in the archive; we'll just want a way to load it into TNA tool.

* Aaron can say more but we're planning to ask agencies about the expected end date of their feeds on each export -- right now we give the end date based on the last calendar which assumes too much.

* I don't understand the details for how to analyze seasonal feeds, the naive question I'd ask is can we identify seasonal feeds automatically or should they be marked in the data upon load (I'm guessing we'd want to mark them).

* It looks like inconsistencies are being checked for (bounds reduced to the lesser of feed dates and calendar dates) thanks to OSU teams' SQL code. But we can audit to make sure all corner cases are handled.

* Having a date range "excluding" seasonal feeds seems pretty easy once seasonal feeds are marked as such.

**Comment by PPaulsonOregonDOT** [comment]
@ed-g Generally, we know which feeds are seasonal (at this point, I think it's just Klamath Shuttle and Columbia Gorge Express).

**Comment by PPaulsonOregonDOT** [comment]
One observation that I just made related to this is that the floating box with all of the Oregon Transportation Agencies (OTA) currently shows now agencies with expired feeds, which would suggest that at least today should be considered a valid day, and I believe this entire week should qualify. However, in looking at the data graph, there are no days when all feeds are valid. This might be related to issue #32, but it's unclear where in the process the date information is getting corrupted/broken.

**Comment by ed-g** [comment]
@antrim I'll let you make a time estimate here

**Comment by ODOT-RPTD-mb** [comment]
@PPaulsonOregonDOT  Phil comment ported from closed issue:
This points to a bigger conversation that we need to have about what the tool looks at in terms of "up to date" data. RVTD's feed doesn't expire until 2025, but their calendar.txt end date is 9/1 on the old feed and the same file has a start date of 9/25 in the newest feed, which is the same date as it was refreshed on oregon-gtfs.com. The feed validator didn't throw an issue with this feed, which would suggest it's not out of spec, but it causes some problematic behavior in the tool.

**Comment by ODOT-RPTD-mb** [comment]
@antrim @PPaulsonOregonDOT @ed-g  - word file with some additional notes on GTFS feed set updates and archiving.
[TNAST GTFS DATABASE UPDATE NOTES.docx](https://github.com/pouyalireza/TNAST_MAVEN/files/1519952/TNAST.GTFS.DATABASE.UPDATE.NOTES.docx)
