### ISSUE TITLE
Show the date range of GTFS dataset validity in the UI

### ISSUE THREAD

**Issue by antrim** [ODOT-PTS/TNExT#5]
Make easily available through the TNA UI, for each GTFS dataset, the date range (if any), during which all feeds in the GTFS dataset are valid. (maybe at bottom of map agency list?)

This is already being done in the Floating dialog box(i.e the start and end date of each feed is displayed for each agency as the tool tip as shown below).Each of the GTFS feeds have a different start and end dates so a generalized date of expiry might not be feasible. 

Even though we can look at the feed dates of 65 feeds, we are interested in having the app show the period of (if any) of all feeds being within their period of validity. 

![image](https://user-images.githubusercontent.com/6495639/29435362-a34505ae-835b-11e7-81b7-e50a0d89c426.png)

**Comment by antrim** [comment]
This looks awesome, thanks! cross off task 2.
 
From: Venkatesa Prasad, Srinivas Prabandh [mailto:venkates@oregonstate.edu] 
Sent: Monday, August 14, 2017 8:07 PM
To: BARNES Matthew M
Cc: portedav1; Benjamin George Fields; PAULSON Philip
Subject: Re: Question based on task 2
 
Matthew,
 
I have been working on the development of task 2.As part of this task, a date range for which all feeds are valid is calculated and shown in the Floating dialog box:
 
![image002](https://user-images.githubusercontent.com/6495639/29435423-dcb78960-835b-11e7-801c-87a9035b86f3.png)

 
Clicking on the date range shows a visualization of all the feeds for that given database along with the period in which all feeds are valid(labelled as overlap):
 
![image004](https://user-images.githubusercontent.com/6495639/29435430-e355ac16-835b-11e7-98bb-293bcd749297.png)
![image006](https://user-images.githubusercontent.com/6495639/29435434-e8c4a24c-835b-11e7-9bdd-bca3407427aa.jpg)

Please let me know if this addresses task 2 and also if you have any questions about this.Thank you for your time.
 
Regards,
Srinivas  
 
On Sat, Jul 22, 2017 at 1:11 PM, BARNES Matthew M <Matthew.M.BARNES@odot.state.or.us> wrote:
Date range In which all feeds are "valid". For example if we have three feeds; Start 1-jan-2017 - end 15 jan 2017, start 4 jan 2016 end 2 jan 2017, and start 3 feb 2017 end 31 dec 2018, then there is no date range for which all feeds are "valid".
 
The more important aspect of basing analysis on the best available data remains on the data creation side and is not an application side issue:
Are the feed date ranges really appropriate... do they match use of calendar files and actual network state, etc...
From: Venkatesa Prasad, Srinivas Prabandh [venkates@oregonstate.edu]
Sent: Tuesday, July 18, 2017 3:20 PM
To: BARNES Matthew M; portedav1; Benjamin George Fields
Subject: Question based on task 2

Matthew,
 
Task 2,in the tasks you sent us for the summ​er asked us to find a date range for which all the GTFS feeds within a data set are valid.For this task are you interested in finding out the dates within which all the GTFS feeds are valid i.e from C to D or the date range within which at least one of the feeds are valid i.e from A to B?Thank you for your time.
 
![image006](https://user-images.githubusercontent.com/6495639/29435441-f185265e-835b-11e7-91b2-0417aaf5f3d7.jpg)
 
Regards,
Srinivas

**Comment by PPaulsonOregonDOT** [comment]
Two notes on the functionality of the tool posted above, from the Fall 2016 database:
1) On the graph style output above, the tooltip for the overlap only include the months i.e. Aug-Oct. 2016
2. These months do not match the dates listed on the floating tool bar, which run from the end of July 24th to September.

Can you clarify what these two date ranges measure, and make sure that they're internally consistent if they measure the same range?

**Comment by ODOT-RPTD-mb** [comment]
Possible modification to "Valid Date Range:" posting:
Because the current "no valid date range" message could be disturbing to less experienced TNA tool users, I suggest that we use a "Best Date Range" message paired with one or two percentage indicators.

For example:
**BEST DATE RANGE:**
10/11/2016 – 10/22/2016 (85% Agencies, 99% Service Miles)
 or
**BEST DATE RANGE:**
5/26/2017- 6/29/2017 (100% Agencies, 100% Service Miles)

Where application identifies the date range with the most valid service miles, then most valid agencies with at least 7 contiguous days of duration.

![image](https://user-images.githubusercontent.com/8129162/29469013-62abbcf4-83fb-11e7-8484-e2b0ffef4601.png)

**Comment by pouyalireza** [comment]
@PPaulsonOregonDOT  The dates should be consistent now this has been addressed in commit  2ab8458097531ed835e6e0cb2e6e083b35448e31

**Comment by ed-g** [comment]
Closing this unless @PPaulsonOregonDOT you think there is more work to be done here.

**Comment by PPaulsonOregonDOT** [comment]
@ed-g, I apologize for the delay in my response, but in the floating dialog box, I'm only seeing 60 agencies, when I would expect to see 65+, with agencies that have expired GTFS feeds displayed in red. This functionality is important to have in order to give user's a warning about what agencies they should expect to see excluded from the results of reports that they run.

**Comment by PPaulsonOregonDOT** [comment]
This issue appears to be resolved, given the functionality currently in the tool and the resolution of the OTA floating box issue.
