### ISSUE TITLE
admin page breaks if dbInfo.csv refers to nonexistent databases

### ISSUE THREAD

**Issue by ed-g** [ODOT-PTS/TNExT#58]
That's sort of OK. The problem is we don't even get an error message so it's hard to diagnose which database load failed.

Add a logging message when dbInfo.csv is loaded and the first database connection is attempted, preferably only when there is an error.

System.err.format() function can be used for this.

**Comment by srinivas13794** [comment]
@ed-g Ideally all new databases should be created through the admin interface . Through the process of creation, the database is added to postgres and also to the dbinfo.csv file.So moving forward, the problem of a non existent database should not arise as creation,deletion and modification of databases should take place through the admin interface

**Comment by ed-g** [comment]
I agree with regard to the proper work flow.

The problem is if anything goes wrong is is exceedingly difficult to diagnose a problem as we have seen. So a little logging message goes a long way.

**Comment by ed-g** [comment]
Re prioritizing low since there are other things we need to solve which are more urgent.

**Comment by ed-g** [comment]
Good value would be 2-3 hours spent adding error messages when config files such as this are referenced.
