### ISSUE TITLE
Make raw GTFS feeds available for debugging in case data looks funny in TNAST

### ISSUE THREAD

**Issue by ed-g** [ODOT-PTS/TNExT#6]
Develop and communicate a process by which raw GTFS feeds sets that are imported to the TNA tool are available for ODOT/OSU/Trillium inspection. These feeds should not be available to the general public. [Trillium is the logical lead on this activity]

This could be as simple as dumping zip files (of feed zip files) on a protected cloud location, with the zip file name corresponding to the TNA dataset name.

> Right now we have a box folder that stores the backups for each database.

**Comment by ed-g** [comment]
Postgres database backups are great to have.

What we need in addition are copies of gtfs zip files used to build the Postgresql import.

**Comment by ODOT-RPTD-mb** [comment]
Develop process for saving zipped GTFS files associated with a TNAST db in an easy to access location, probably with Postgres database backups, each time a new TNAST db is created. More important that this happens for db creation going forward, than for past TNAST db.

**Comment by ed-g** [comment]
@tnatool @pouyalireza @srinivas13794 

Where is a link to the posgres backup files? Can you post here and/or link on the wiki: https://github.com/pouyalireza/TNAST_MAVEN/wiki

**Comment by ed-g** [comment]
Ok we're halfway there. Found them here: 

https://drive.google.com/drive/folders/0Bx4Zxars8NaNOWNxTlctME92OGc

Would you please upload Spring 2017 dump to this folder?

**Comment by ed-g** [comment]
Oops these comments should have been for #33

**Comment by ed-g** [comment]
All these gtfs files get uploaded to a resource directory. 

A simple solution would be:
* Make the upload directory specific per datatabase, using the id number from dbInfo.csv.
* Don't delete them after loading.

We could use the same method to make raw files available for other data uploaded to TNA tool.

Only downside is that uploading the same file twice will probably overwrite the earlier version, or maybe even fail. Depending on how upload code is written. We'll need to test this and choose an alternative. I vote for "overwrite" since the data will also be overwritten in the database. But I could see a situation where the db load fails but the file upload succeeds leaving broken data in the raw file. If this matters we should actually design a retention mechanism.

**Comment by ed-g** [comment]
I thought that I had kept the files in the /etc directory but they're still getting deleted.

For now it might be easier to have a manual process where we maintain a copy of any uploaded GTFS on the server under an SFTP account.

**Comment by ODOT-RPTD-mb** [comment]
do we have an existing body of documentation of new db creation process for Trillium? GTFS saving process should be part of such documentation

**Comment by ed-g** [comment]
Creating a manual process and documenting it is 2-3 hours. The trick is making it easy to remember to adhere to the process.
