### ISSUE TITLE
Shapefile Exporter Broken

### ISSUE THREAD

**Issue by PPaulsonOregonDOT** [ODOT-PTS/TNExT#65]
I just tried to run the shapefile export function on the September database in the TNA version of the tool, and recieved the following pop-up message:

"HTTP Status 404 - /%3Chtml%3E%3Chead%3E%3Ctitle%3EApache%20Tomcat/7.0.76%20-%20Error%20report%3C/title%3E%3Cstyle%3E%3C!--H1%20%7Bfont-family:Tahoma,Arial,sans-serif;color:white;background-color:

type Status report

message /%3Chtml%3E%3Chead%3E%3Ctitle%3EApache%20Tomcat/7.0.76%20-%20Error%20report%3C/title%3E%3Cstyle%3E%3C!--H1%20%7Bfont-family:Tahoma,Arial,sans-serif;color:white;background-color:

description The requested resource is not available."

This is a message I'm somewhat familiar with from trying to get reports on the ODOT network, but I tried it off the network, with the same result. I was trying to download all of the routes, but even trying to download the routes from one agency causes this error.

**Comment by srinivas13794** [comment]
@PPaulsonOregonDOT  Just to confirm that you were using the Trillium server to generate these shape files. @ed-g I tested out few other databases and they seemed to work, there seems to be a problem with the September 2017 database.

**Comment by PPaulsonOregonDOT** [comment]
@srinivas13794 That is correct, I am using the TNA server. I ran the same report/tool for the May 2017 and April 2017 databases, and received the same message.

**Comment by ed-g** [comment]
@PPaulsonOregonDOT just to echo Srinivas here. There are four TNA servers:

OSU development (port 8080)
OSU production (port 80)

Trillium development (port 8080)
Trillium production (port 80)

OSU servers are useful for reference but are no longer receiving code updates but may potentially get data updates for testing purposes.

Trillium servers are receiving code and data updates.

It might be significant, were you using the *development* or *production* Trillium TNA server?

**Comment by ed-g** [comment]
Hi @PPaulsonOregonDOT 

Did you export stops or routes? Which agencies were selected?

I'm seeing an error when I attempt to export Albany's routes.

It's opening a popup window which contains a URL quoting a tomcat error message. Bizzare.

`http://tna.trilliumtransit.com:8080/%3Chtml%3E%3Chead%3E%3Ctitle%3EApache%20Tomcat/7.0.76%20-%20Error%20report%3C/title%3E%3Cstyle%3E%3C!--H1%20%7Bfont-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;}%20H2%20{font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;}%20H3%20{font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;}%20BODY%20{font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;}%20B%20{font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;}%20P%20{font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A%20{color%20:%20black;}A.name%20{color%20:%20black;}HR%20{color%20:%20#525D76;}--%3E%3C/style%3E%20%3C/head%3E%3Cbody%3E%3Ch1%3EHTTP%20Status%20500%20-%20java.io.FileNotFoundException:%20/var/lib/tomcat/webapps-development/ROOT/WEB-INF/classes/../../src/main/resources/admin/resources/databaseParams.csv%20(No%20such%20file%20or%20directory)%3C/h1%3E%3CHR%20size=%221%22%20noshade=%22noshade%22%3E%3Cp%3E%3Cb%3Etype%3C/b%3E%20Exception%20report%3C/p%3E%3Cp%3E%3Cb%3Emessage%3C/b%3E%20%3Cu%3Ejava.io.FileNotFoundException:%20/var/lib/tomcat/webapps-development/ROOT/WEB-INF/classes/../../src/main/resources/admin/resources/databaseParams.csv%20(No%20such%20file%20or%20directory)%3C/u%3E%3C/p%3E%3Cp%3E%3Cb%3Edescription%3C/b%3E%20%3Cu%3EThe%20server%20encountered%20an%20internal%20error%20that%20prevented%20it%20from%20fulfilling%20this%20request.%3C/u%3E%3C/p%3E%3Cp%3E%3Cb%3Eexception%3C/b%3E%20%3Cpre%3Ejavax.servlet.ServletException:%20java.io.FileNotFoundException:%20/var/lib/tomcat/webapps-development/ROOT/WEB-INF/classes/../../src/main/resources/admin/resources/databaseParams.csv%20(No%20such%20file%20or%20directory)com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:423)com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537)com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:699)javax.servlet.http.HttpServlet.service(HttpServlet.java:731)org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)%3C/pre%3E%3C/p%3E%3Cp%3E%3Cb%3Eroot%20cause%3C/b%3E%20%3Cpre%3Ejava.io.FileNotFoundException:%20/var/lib/tomcat/webapps-development/ROOT/WEB-INF/classes/../../src/main/resources/admin/resources/databaseParams.csv%20(No%20such%20file%20or%20directory)java.io.FileInputStream.open0(Native%20Method)java.io.FileInputStream.open(FileInputStream.java:195)java.io.FileInputStream.&lt;init&gt;(FileInputStream.java:138)java.io.FileInputStream.&lt;init&gt;(FileInputStream.java:93)java.io.FileReader.&lt;init&gt;(FileReader.java:58)com.webapp.api.Queries.getShapeFile(Queries.java:248)sun.reflect.NativeMethodAccessorImpl.invoke0(Native%20Method)sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.lang.reflect.Method.invoke(Method.java:498)com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ObjectOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:237)com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:70)com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:279)com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:136)com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:86)com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:136)com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:74)com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1347)com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1279)com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1229)com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1219)com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:419)com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537)com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:699)javax.servlet.http.HttpServlet.service(HttpServlet.java:731)org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)%3C/pre%3E%3C/p%3E%3Cp%3E%3Cb%3Enote%3C/b%3E%20%3Cu%3EThe%20full%20stack%20trace%20of%20the%20root%20cause%20is%20available%20in%20the%20Apache%20Tomcat/7.0.76%20logs.%3C/u%3E%3C/p%3E%3CHR%20size=%221%22%20noshade=%22noshade%22%3E%3Ch3%3EApache%20Tomcat/7.0.76%3C/h3%3E%3C/body%3E%3C/html%3E`

**Comment by ed-g** [comment]
This URL fails.

http://tna.trilliumtransit.com:8080/TNAtoolAPI-Webapp/queries/transit/getshapefile?agencyids=456&flag=routes&dbName=september17&username=admin&dbIndex=10

**Comment by PPaulsonOregonDOT** [comment]
@ed-g To clarify above, I was using a trillium server.  As an update, I just tested the export tool on both TNA servers using the September database, exporting albany routes. Hitting the export button creates an about:blank pop-up window, but I don't see a download, and I'm not seeing the tomcat error message any longer.

**Comment by ed-g** [comment]
Something I noticed that may help during the debugging process.

It seems like tomcat java applications "cache" the existence of errors.

In other words tomcat will show an error the first time it is encountered, but and afterwards a page will still fail but no error is shown.

**Comment by ODOT-RPTD-mb** [comment]
exporter functionality needs some rework, not just bug fix.

**Comment by ed-g** [comment]
Oh the error might just because the databaseParams.csv (another redundant config file) is missing from the source directory since I attempted to move everything to /etc.

So fixing the error is probably only 1hr.

But rework, I'll say 6-10 hours.

**Comment by ODOT-RPTD-mb** [comment]
@PPaulsonOregonDOT Shapefile Exporter

Revised Functionality
1)	Export stops and routes only. Date selection, and GTFS database are user input parameters. Exports data for “current” feeds, feed within feed start and end dates, even if not within calendar date range.
2)	Export stops and routes and trips and times. Date selection, and GTFS database are user input parameters. Exports data valid for day. For example a stop with no visits or a route with no runs on the selected day will not be exported.
3)	Export demographics. Population database is user input parameter. For each block internal point export all available associated demographic data.

**Comment by drewda** [comment]
Item `1.` in that list has been addressed in pull request #80

**Comment by irees** [comment]
Feature additions `2` and `3` are addressed by pull requests #104 and #106.
