### ISSUE TITLE
refactor query code to use a VIEW

### ISSUE THREAD

**Issue by ed-g** [ODOT-PTS/TNExT#76]
Then those VIEW results can be available to any other database querying including for example qgis.

**Comment by PPaulsonOregonDOT** [comment]
Would it be possible to set the queries for the stable version of the tool to these views, but keep the development version linked to the current database as a method of separating the two versions?

**Comment by ed-g** [comment]
The stable and development versions currently share a database. We can keep them on the same database or create a new database for the development version, and that's independant of whether we refactor query code to use a VIEW.

**Comment by PPaulsonOregonDOT** [comment]
I think we should split the databases, because we want to have one instance of the tool up and running while we update the other. Case in point, I tried to update the Sept17 database, and it has crashed that database in both tools for two weeks.

**Comment by ed-g** [comment]
Ok I can see the need. The trick is it's handy to be able to test code changes independently of data.

The way this can be structured is a grid

 \ | production code | development code
---- | ----- | -----
**production data** | production | staging
**testing data** |  testing | developent

**Comment by PPaulsonOregonDOT** [comment]
I definitely like this arrangement, my only concern is how much additional work it will create to implement this upfront.

**Comment by ed-g** [comment]
Takes some process and configuration time, but it's straightforward.

We can just dump/restore each database to a "testing" version for example testingwinter17. Then change the config in the testing and development servers to point to those databases.

**Comment by ODOT-RPTD-mb** [comment]
Breaking out db organization as a separate issue #77

**Comment by ODOT-RPTD-mb** [comment]
@ed Are there efficiency benefits to be had by combining issue #13 with view re-factoring?

Can view refactoring be done incrementally, phased over time?

Work time estimate for refactoring?

**Comment by ODOT-RPTD-mb** [comment]
In light of interline work. Is this still relevent?

**Comment by PPaulsonOregonDOT** [comment]
It would appear that this issue has been resolved via interline work, as the production and development instances of the tool appear to have access to different database sets. If my understanding of this issue is incorrect, @irees @drewda, please re-open this issue.
