### ISSUE TITLE
ISSUE ATTACK SEQUENCING

### ISSUE THREAD

**Issue by ODOT-RPTD-mb** [ODOT-PTS/TNExT#79]
@ed-g @PPaulsonOregonDOT 
This issue addresses work sequencing of other issues. See embedded image for proposed sequencing through most or all of January.

![image](https://user-images.githubusercontent.com/8129162/33179002-d003b582-d01c-11e7-9560-e04579258227.png)

**Comment by antrim** [comment]
Issues (in order):
#77 reorg db
#78 New GTFS snapshot
#75 better log messages
#67 route mile measures inconsistency
#65 Shapefile exporter bug broken
#22 Time of day reports
