### ISSUE TITLE
Develop documention during installation of TNAST tool

### ISSUE THREAD

**Issue by ed-g** [ODOT-PTS/TNExT#9]
Based on any difficulties I run into. Suggest documentation improvements.

**Comment by ed-g** [comment]
Assign to Ed.

**Comment by ed-g** [comment]
AKA "Look for and act on low effort opportunities to reduce barriers to creation of a TNA tool instance by third parties."

**Comment by antrim** [comment]
Where should we put the documentation -- in this GitHub repo?

Related issue/question: #1.

**Comment by ed-g** [comment]
It sounds like docs should be integrated with the https://github.com/pouyalireza/TNAST_MAVEN/blob/master/README.md file

@pouyalireza does that seem like the best location for install docs?

**Comment by pouyalireza** [comment]
@ed-g  Yes.

**Comment by ed-g** [comment]
Once the database configuration has solidified, add documentation.

Main difference is I'm moving all the xml config files whose data will change depending on the installation to a configuration directory, suggested `/etc/tnatool` on Linux/mac and `c:/Users/tnatool/config` on Windows, rather than the source directory.

Configuration is via a Java property set via tomcat, `edu.oregonstate.tnatool.ConfigurationDirectory`

Config overview https://github.com/pouyalireza/TNAST_MAVEN/issues/51#issuecomment-328984671

Specific files listed https://github.com/pouyalireza/TNAST_MAVEN/issues/54#issuecomment-328990942

**Comment by ed-g** [comment]
Current set up is madness based on the fact that the config files are scattered throughout the:
* source directory
* jar file
* /etc

And no clear distinction is made within the code as to where to find config files in any given scenario.

We need to fix this, so that installation process can be sane, and then we can document that new process.

**Comment by ODOT-RPTD-mb** [comment]
To what degree, did interline work simplify the installation process. Can a moderately skilled technician create a TNExT instance?
